//*****************************************************************************
// The file is automatically generated by the program, do not manually modify. 
//*****************************************************************************

package org.github.spring.base.entity;

import java.io.Serializable;
import lombok.EqualsAndHashCode;
import org.github.spring.base.key.ArticleKey;

/**
 * ArticleEntity [ sampledb.article ].
 *
 * @author MyBatisGenerator
 * @version 2017-09-21
 */
@EqualsAndHashCode(callSuper = true)
@SuppressWarnings("serial")
public class ArticleEntity extends ArticleKey implements Serializable {
  /** title [ article.title ]. */
  private String title;

  /** content [ article.content ]. */
  private String content;

  /** image [ article.image ]. */
  private String image;

  /** time [ article.time ]. */
  private String time;

  /** editer [ article.editer ]. */
  private String editer;

  /** count [ article.count ]. */
  private Integer count;

  /** count1 [ article.count1 ]. */
  private Integer count1;

  /** flag [ article.flag ]. */
  private String type;

  /** notice [ article.notice ]. */
  private String notice;

  /** keywords [ article.keywords ]. */
  private String keywords;

  /**
   * GET title [ article.title ].
   *
   * @return java.lang.String
   */
  public String getTitle() {
    return title;
  }

  /**
   * WITH title [ article.title ].
   *
   * @param title java.lang.String
   * @return org.github.spring.base.entity.ArticleEntity
   */
  public ArticleEntity withTitle(String title) {
    this.setTitle(title);
    return this;
  }

  /**
   * SET title [ article.title ].
   *
   * @param title java.lang.String
   */
  public void setTitle(String title) {
    this.title = title == null ? null : title.trim();
  }

  /**
   * GET content [ article.content ].
   *
   * @return java.lang.String
   */
  public String getContent() {
    return content;
  }

  /**
   * WITH content [ article.content ].
   *
   * @param content java.lang.String
   * @return org.github.spring.base.entity.ArticleEntity
   */
  public ArticleEntity withContent(String content) {
    this.setContent(content);
    return this;
  }

  /**
   * SET content [ article.content ].
   *
   * @param content java.lang.String
   */
  public void setContent(String content) {
    this.content = content == null ? null : content.trim();
  }

  /**
   * GET image [ article.image ].
   *
   * @return java.lang.String
   */
  public String getImage() {
    return image;
  }

  /**
   * WITH image [ article.image ].
   *
   * @param image java.lang.String
   * @return org.github.spring.base.entity.ArticleEntity
   */
  public ArticleEntity withImage(String image) {
    this.setImage(image);
    return this;
  }

  /**
   * SET image [ article.image ].
   *
   * @param image java.lang.String
   */
  public void setImage(String image) {
    this.image = image == null ? null : image.trim();
  }

  /**
   * GET time [ article.time ].
   *
   * @return java.lang.String
   */
  public String getTime() {
    return time;
  }

  /**
   * WITH time [ article.time ].
   *
   * @param time java.lang.String
   * @return org.github.spring.base.entity.ArticleEntity
   */
  public ArticleEntity withTime(String time) {
    this.setTime(time);
    return this;
  }

  /**
   * SET time [ article.time ].
   *
   * @param time java.lang.String
   */
  public void setTime(String time) {
    this.time = time == null ? null : time.trim();
  }

  /**
   * GET editer [ article.editer ].
   *
   * @return java.lang.String
   */
  public String getEditer() {
    return editer;
  }

  /**
   * WITH editer [ article.editer ].
   *
   * @param editer java.lang.String
   * @return org.github.spring.base.entity.ArticleEntity
   */
  public ArticleEntity withEditer(String editer) {
    this.setEditer(editer);
    return this;
  }

  /**
   * SET editer [ article.editer ].
   *
   * @param editer java.lang.String
   */
  public void setEditer(String editer) {
    this.editer = editer == null ? null : editer.trim();
  }

  /**
   * GET count [ article.count ].
   *
   * @return java.lang.Integer
   */
  public Integer getCount() {
    return count;
  }

  /**
   * WITH count [ article.count ].
   *
   * @param count java.lang.Integer
   * @return org.github.spring.base.entity.ArticleEntity
   */
  public ArticleEntity withCount(Integer count) {
    this.setCount(count);
    return this;
  }

  /**
   * SET count [ article.count ].
   *
   * @param count java.lang.Integer
   */
  public void setCount(Integer count) {
    this.count = count;
  }

  /**
   * GET count1 [ article.count1 ].
   *
   * @return java.lang.Integer
   */
  public Integer getCount1() {
    return count1;
  }

  /**
   * WITH count1 [ article.count1 ].
   *
   * @param count1 java.lang.Integer
   * @return org.github.spring.base.entity.ArticleEntity
   */
  public ArticleEntity withCount1(Integer count1) {
    this.setCount1(count1);
    return this;
  }

  /**
   * SET count1 [ article.count1 ].
   *
   * @param count1 java.lang.Integer
   */
  public void setCount1(Integer count1) {
    this.count1 = count1;
  }

  /**
   * GET flag [ article.flag ].
   *
   * @return java.lang.String
   */
  public String getType() {
    return type;
  }

  /**
   * WITH flag [ article.flag ].
   *
   * @param type java.lang.String
   * @return org.github.spring.base.entity.ArticleEntity
   */
  public ArticleEntity withType(String type) {
    this.setType(type);
    return this;
  }

  /**
   * SET flag [ article.flag ].
   *
   * @param type java.lang.String
   */
  public void setType(String type) {
    this.type = type == null ? null : type.trim();
  }

  /**
   * GET notice [ article.notice ].
   *
   * @return java.lang.String
   */
  public String getNotice() {
    return notice;
  }

  /**
   * WITH notice [ article.notice ].
   *
   * @param notice java.lang.String
   * @return org.github.spring.base.entity.ArticleEntity
   */
  public ArticleEntity withNotice(String notice) {
    this.setNotice(notice);
    return this;
  }

  /**
   * SET notice [ article.notice ].
   *
   * @param notice java.lang.String
   */
  public void setNotice(String notice) {
    this.notice = notice == null ? null : notice.trim();
  }

  /**
   * GET keywords [ article.keywords ].
   *
   * @return java.lang.String
   */
  public String getKeywords() {
    return keywords;
  }

  /**
   * WITH keywords [ article.keywords ].
   *
   * @param keywords java.lang.String
   * @return org.github.spring.base.entity.ArticleEntity
   */
  public ArticleEntity withKeywords(String keywords) {
    this.setKeywords(keywords);
    return this;
  }

  /**
   * SET keywords [ article.keywords ].
   *
   * @param keywords java.lang.String
   */
  public void setKeywords(String keywords) {
    this.keywords = keywords == null ? null : keywords.trim();
  }
}