//*****************************************************************************
// The file is automatically generated by the program, do not manually modify. 
//*****************************************************************************

package org.github.spring.base.entity;

import java.io.Serializable;
import lombok.EqualsAndHashCode;
import org.github.spring.base.key.ArtStatKey;

/**
 * ArtStatEntity [ sampledb.t_art_stat ].
 *
 * @author MyBatisGenerator
 * @version 2017-09-21
 */
@EqualsAndHashCode(callSuper = true)
@SuppressWarnings("serial")
public class ArtStatEntity extends ArtStatKey implements Serializable {
  /** 文章点击数 [ t_art_stat.read_count ]. */
  private Integer readCount;

  /** 点赞数 [ t_art_stat.upvote ]. */
  private Integer upvote;

  /**
   * GET 文章点击数 [ t_art_stat.read_count ].
   *
   * @return java.lang.Integer
   */
  public Integer getReadCount() {
    return readCount;
  }

  /**
   * WITH 文章点击数 [ t_art_stat.read_count ].
   *
   * @param readCount java.lang.Integer
   * @return org.github.spring.base.entity.ArtStatEntity
   */
  public ArtStatEntity withReadCount(Integer readCount) {
    this.setReadCount(readCount);
    return this;
  }

  /**
   * SET 文章点击数 [ t_art_stat.read_count ].
   *
   * @param readCount java.lang.Integer
   */
  public void setReadCount(Integer readCount) {
    this.readCount = readCount;
  }

  /**
   * GET 点赞数 [ t_art_stat.upvote ].
   *
   * @return java.lang.Integer
   */
  public Integer getUpvote() {
    return upvote;
  }

  /**
   * WITH 点赞数 [ t_art_stat.upvote ].
   *
   * @param upvote java.lang.Integer
   * @return org.github.spring.base.entity.ArtStatEntity
   */
  public ArtStatEntity withUpvote(Integer upvote) {
    this.setUpvote(upvote);
    return this;
  }

  /**
   * SET 点赞数 [ t_art_stat.upvote ].
   *
   * @param upvote java.lang.Integer
   */
  public void setUpvote(Integer upvote) {
    this.upvote = upvote;
  }
}