//*****************************************************************************
// The file is automatically generated by the program, do not manually modify. 
//*****************************************************************************

package org.github.spring.base.entity;

import java.io.Serializable;
import lombok.EqualsAndHashCode;
import org.github.spring.footstone.AbstractEntity;

/**
 * AuthoritiesEntity [ sampledb.authorities ].
 *
 * @author MyBatisGenerator
 * @version 2017-09-21
 */
@EqualsAndHashCode(callSuper = true)
@SuppressWarnings("serial")
public class AuthoritiesEntity extends AbstractEntity implements Serializable {
  /** username [ authorities.username ]. */
  private String username;

  /** authority [ authorities.authority ]. */
  private String authority;

  /**
   * GET username [ authorities.username ].
   *
   * @return java.lang.String
   */
  public String getUsername() {
    return username;
  }

  /**
   * WITH username [ authorities.username ].
   *
   * @param username java.lang.String
   * @return org.github.spring.base.entity.AuthoritiesEntity
   */
  public AuthoritiesEntity withUsername(String username) {
    this.setUsername(username);
    return this;
  }

  /**
   * SET username [ authorities.username ].
   *
   * @param username java.lang.String
   */
  public void setUsername(String username) {
    this.username = username == null ? null : username.trim();
  }

  /**
   * GET authority [ authorities.authority ].
   *
   * @return java.lang.String
   */
  public String getAuthority() {
    return authority;
  }

  /**
   * WITH authority [ authorities.authority ].
   *
   * @param authority java.lang.String
   * @return org.github.spring.base.entity.AuthoritiesEntity
   */
  public AuthoritiesEntity withAuthority(String authority) {
    this.setAuthority(authority);
    return this;
  }

  /**
   * SET authority [ authorities.authority ].
   *
   * @param authority java.lang.String
   */
  public void setAuthority(String authority) {
    this.authority = authority == null ? null : authority.trim();
  }
}