//*****************************************************************************
// The file is automatically generated by the program, do not manually modify. 
//*****************************************************************************

package org.github.spring.base.entity;

import java.io.Serializable;
import lombok.EqualsAndHashCode;
import org.github.spring.base.key.CritiqueKey;

/**
 * CritiqueEntity [ sampledb.critique ].
 *
 * @author MyBatisGenerator
 * @version 2017-09-21
 */
@EqualsAndHashCode(callSuper = true)
@SuppressWarnings("serial")
public class CritiqueEntity extends CritiqueKey implements Serializable {
  /** article_id [ critique.article_id ]. */
  private Integer articleId;

  /** content [ critique.content ]. */
  private String content;

  /** name [ critique.name ]. */
  private String name;

  /** time [ critique.time ]. */
  private String time;

  /** photo [ critique.photo ]. */
  private String photo;

  /** flag [ critique.flag ]. */
  private String type;

  /** notice [ critique.notice ]. */
  private String notice;

  /**
   * GET article_id [ critique.article_id ].
   *
   * @return java.lang.Integer
   */
  public Integer getArticleId() {
    return articleId;
  }

  /**
   * WITH article_id [ critique.article_id ].
   *
   * @param articleId java.lang.Integer
   * @return org.github.spring.base.entity.CritiqueEntity
   */
  public CritiqueEntity withArticleId(Integer articleId) {
    this.setArticleId(articleId);
    return this;
  }

  /**
   * SET article_id [ critique.article_id ].
   *
   * @param articleId java.lang.Integer
   */
  public void setArticleId(Integer articleId) {
    this.articleId = articleId;
  }

  /**
   * GET content [ critique.content ].
   *
   * @return java.lang.String
   */
  public String getContent() {
    return content;
  }

  /**
   * WITH content [ critique.content ].
   *
   * @param content java.lang.String
   * @return org.github.spring.base.entity.CritiqueEntity
   */
  public CritiqueEntity withContent(String content) {
    this.setContent(content);
    return this;
  }

  /**
   * SET content [ critique.content ].
   *
   * @param content java.lang.String
   */
  public void setContent(String content) {
    this.content = content == null ? null : content.trim();
  }

  /**
   * GET name [ critique.name ].
   *
   * @return java.lang.String
   */
  public String getName() {
    return name;
  }

  /**
   * WITH name [ critique.name ].
   *
   * @param name java.lang.String
   * @return org.github.spring.base.entity.CritiqueEntity
   */
  public CritiqueEntity withName(String name) {
    this.setName(name);
    return this;
  }

  /**
   * SET name [ critique.name ].
   *
   * @param name java.lang.String
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }

  /**
   * GET time [ critique.time ].
   *
   * @return java.lang.String
   */
  public String getTime() {
    return time;
  }

  /**
   * WITH time [ critique.time ].
   *
   * @param time java.lang.String
   * @return org.github.spring.base.entity.CritiqueEntity
   */
  public CritiqueEntity withTime(String time) {
    this.setTime(time);
    return this;
  }

  /**
   * SET time [ critique.time ].
   *
   * @param time java.lang.String
   */
  public void setTime(String time) {
    this.time = time == null ? null : time.trim();
  }

  /**
   * GET photo [ critique.photo ].
   *
   * @return java.lang.String
   */
  public String getPhoto() {
    return photo;
  }

  /**
   * WITH photo [ critique.photo ].
   *
   * @param photo java.lang.String
   * @return org.github.spring.base.entity.CritiqueEntity
   */
  public CritiqueEntity withPhoto(String photo) {
    this.setPhoto(photo);
    return this;
  }

  /**
   * SET photo [ critique.photo ].
   *
   * @param photo java.lang.String
   */
  public void setPhoto(String photo) {
    this.photo = photo == null ? null : photo.trim();
  }

  /**
   * GET flag [ critique.flag ].
   *
   * @return java.lang.String
   */
  public String getType() {
    return type;
  }

  /**
   * WITH flag [ critique.flag ].
   *
   * @param type java.lang.String
   * @return org.github.spring.base.entity.CritiqueEntity
   */
  public CritiqueEntity withType(String type) {
    this.setType(type);
    return this;
  }

  /**
   * SET flag [ critique.flag ].
   *
   * @param type java.lang.String
   */
  public void setType(String type) {
    this.type = type == null ? null : type.trim();
  }

  /**
   * GET notice [ critique.notice ].
   *
   * @return java.lang.String
   */
  public String getNotice() {
    return notice;
  }

  /**
   * WITH notice [ critique.notice ].
   *
   * @param notice java.lang.String
   * @return org.github.spring.base.entity.CritiqueEntity
   */
  public CritiqueEntity withNotice(String notice) {
    this.setNotice(notice);
    return this;
  }

  /**
   * SET notice [ critique.notice ].
   *
   * @param notice java.lang.String
   */
  public void setNotice(String notice) {
    this.notice = notice == null ? null : notice.trim();
  }
}