//*****************************************************************************
// The file is automatically generated by the program, do not manually modify. 
//*****************************************************************************

package org.github.spring.base.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.EqualsAndHashCode;
import org.github.spring.base.key.LoginLogKey;

/**
 * LoginLogEntity [ sampledb.t_login_log ].
 *
 * @author MyBatisGenerator
 * @version 2017-10-14
 */
@EqualsAndHashCode(callSuper = true)
@SuppressWarnings("serial")
public class LoginLogEntity extends LoginLogKey implements Serializable {
  /** user_id [ t_login_log.user_id ]. */
  private Integer userId;

  /** ip [ t_login_log.ip ]. */
  private String ip;

  /** login_datetime [ t_login_log.login_datetime ]. */
  private Date loginDatetime;

  /**
   * GET user_id [ t_login_log.user_id ].
   *
   * @return java.lang.Integer
   */
  public Integer getUserId() {
    return userId;
  }

  /**
   * WITH user_id [ t_login_log.user_id ].
   *
   * @param userId java.lang.Integer
   * @return org.github.spring.base.entity.LoginLogEntity
   */
  public LoginLogEntity withUserId(Integer userId) {
    this.setUserId(userId);
    return this;
  }

  /**
   * SET user_id [ t_login_log.user_id ].
   *
   * @param userId java.lang.Integer
   */
  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  /**
   * GET ip [ t_login_log.ip ].
   *
   * @return java.lang.String
   */
  public String getIp() {
    return ip;
  }

  /**
   * WITH ip [ t_login_log.ip ].
   *
   * @param ip java.lang.String
   * @return org.github.spring.base.entity.LoginLogEntity
   */
  public LoginLogEntity withIp(String ip) {
    this.setIp(ip);
    return this;
  }

  /**
   * SET ip [ t_login_log.ip ].
   *
   * @param ip java.lang.String
   */
  public void setIp(String ip) {
    this.ip = ip == null ? null : ip.trim();
  }

  /**
   * GET login_datetime [ t_login_log.login_datetime ].
   *
   * @return java.util.Date
   */
  public Date getLoginDatetime() {
    return loginDatetime;
  }

  /**
   * WITH login_datetime [ t_login_log.login_datetime ].
   *
   * @param loginDatetime java.util.Date
   * @return org.github.spring.base.entity.LoginLogEntity
   */
  public LoginLogEntity withLoginDatetime(Date loginDatetime) {
    this.setLoginDatetime(loginDatetime);
    return this;
  }

  /**
   * SET login_datetime [ t_login_log.login_datetime ].
   *
   * @param loginDatetime java.util.Date
   */
  public void setLoginDatetime(Date loginDatetime) {
    this.loginDatetime = loginDatetime;
  }
}