//*****************************************************************************
// The file is automatically generated by the program, do not manually modify. 
//*****************************************************************************

package org.github.spring.base.entity;

import java.io.Serializable;
import lombok.EqualsAndHashCode;
import org.github.spring.base.key.ManagerKey;

/**
 * ManagerEntity [ sampledb.manager ].
 *
 * @author MyBatisGenerator
 * @version 2017-10-14
 */
@EqualsAndHashCode(callSuper = true)
@SuppressWarnings("serial")
public class ManagerEntity extends ManagerKey implements Serializable {
  /** account [ manager.account ]. */
  private String account;

  /** password [ manager.password ]. */
  private String password;

  /** role [ manager.role ]. */
  private String role;

  /** notice [ manager.notice ]. */
  private String notice;

  /**
   * GET account [ manager.account ].
   *
   * @return java.lang.String
   */
  public String getAccount() {
    return account;
  }

  /**
   * WITH account [ manager.account ].
   *
   * @param account java.lang.String
   * @return org.github.spring.base.entity.ManagerEntity
   */
  public ManagerEntity withAccount(String account) {
    this.setAccount(account);
    return this;
  }

  /**
   * SET account [ manager.account ].
   *
   * @param account java.lang.String
   */
  public void setAccount(String account) {
    this.account = account == null ? null : account.trim();
  }

  /**
   * GET password [ manager.password ].
   *
   * @return java.lang.String
   */
  public String getPassword() {
    return password;
  }

  /**
   * WITH password [ manager.password ].
   *
   * @param password java.lang.String
   * @return org.github.spring.base.entity.ManagerEntity
   */
  public ManagerEntity withPassword(String password) {
    this.setPassword(password);
    return this;
  }

  /**
   * SET password [ manager.password ].
   *
   * @param password java.lang.String
   */
  public void setPassword(String password) {
    this.password = password == null ? null : password.trim();
  }

  /**
   * GET role [ manager.role ].
   *
   * @return java.lang.String
   */
  public String getRole() {
    return role;
  }

  /**
   * WITH role [ manager.role ].
   *
   * @param role java.lang.String
   * @return org.github.spring.base.entity.ManagerEntity
   */
  public ManagerEntity withRole(String role) {
    this.setRole(role);
    return this;
  }

  /**
   * SET role [ manager.role ].
   *
   * @param role java.lang.String
   */
  public void setRole(String role) {
    this.role = role == null ? null : role.trim();
  }

  /**
   * GET notice [ manager.notice ].
   *
   * @return java.lang.String
   */
  public String getNotice() {
    return notice;
  }

  /**
   * WITH notice [ manager.notice ].
   *
   * @param notice java.lang.String
   * @return org.github.spring.base.entity.ManagerEntity
   */
  public ManagerEntity withNotice(String notice) {
    this.setNotice(notice);
    return this;
  }

  /**
   * SET notice [ manager.notice ].
   *
   * @param notice java.lang.String
   */
  public void setNotice(String notice) {
    this.notice = notice == null ? null : notice.trim();
  }
}