//*****************************************************************************
// The file is automatically generated by the program, do not manually modify. 
//*****************************************************************************

package org.github.spring.base.entity;

import java.io.Serializable;
import lombok.EqualsAndHashCode;
import org.github.spring.base.key.MeKey;

/**
 * MeEntity [ sampledb.me ].
 *
 * @author MyBatisGenerator
 * @version 2017-10-14
 */
@EqualsAndHashCode(callSuper = true)
@SuppressWarnings("serial")
public class MeEntity extends MeKey implements Serializable {
  /** content [ me.content ]. */
  private String content;

  /** name [ me.name ]. */
  private String name;

  /** notice [ me.notice ]. */
  private String notice;

  /**
   * GET content [ me.content ].
   *
   * @return java.lang.String
   */
  public String getContent() {
    return content;
  }

  /**
   * WITH content [ me.content ].
   *
   * @param content java.lang.String
   * @return org.github.spring.base.entity.MeEntity
   */
  public MeEntity withContent(String content) {
    this.setContent(content);
    return this;
  }

  /**
   * SET content [ me.content ].
   *
   * @param content java.lang.String
   */
  public void setContent(String content) {
    this.content = content == null ? null : content.trim();
  }

  /**
   * GET name [ me.name ].
   *
   * @return java.lang.String
   */
  public String getName() {
    return name;
  }

  /**
   * WITH name [ me.name ].
   *
   * @param name java.lang.String
   * @return org.github.spring.base.entity.MeEntity
   */
  public MeEntity withName(String name) {
    this.setName(name);
    return this;
  }

  /**
   * SET name [ me.name ].
   *
   * @param name java.lang.String
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }

  /**
   * GET notice [ me.notice ].
   *
   * @return java.lang.String
   */
  public String getNotice() {
    return notice;
  }

  /**
   * WITH notice [ me.notice ].
   *
   * @param notice java.lang.String
   * @return org.github.spring.base.entity.MeEntity
   */
  public MeEntity withNotice(String notice) {
    this.setNotice(notice);
    return this;
  }

  /**
   * SET notice [ me.notice ].
   *
   * @param notice java.lang.String
   */
  public void setNotice(String notice) {
    this.notice = notice == null ? null : notice.trim();
  }
}