//*****************************************************************************
// The file is automatically generated by the program, do not manually modify. 
//*****************************************************************************

package org.github.spring.base.entity;

import java.io.Serializable;
import lombok.EqualsAndHashCode;
import org.github.spring.footstone.AbstractEntity;

/**
 * OauthAccessTokenEntity [ sampledb.oauth_access_token ].
 *
 * @author MyBatisGenerator
 * @version 2017-09-21
 */
@EqualsAndHashCode(callSuper = true)
@SuppressWarnings("serial")
public class OauthAccessTokenEntity extends AbstractEntity implements Serializable {
  /** token_id [ oauth_access_token.token_id ]. */
  private String tokenId;

  /** authentication_id [ oauth_access_token.authentication_id ]. */
  private String authenticationId;

  /** user_name [ oauth_access_token.user_name ]. */
  private String userName;

  /** refresh_token [ oauth_access_token.refresh_token ]. */
  private String refreshToken;

  /**
   * GET token_id [ oauth_access_token.token_id ].
   *
   * @return java.lang.String
   */
  public String getTokenId() {
    return tokenId;
  }

  /**
   * WITH token_id [ oauth_access_token.token_id ].
   *
   * @param tokenId java.lang.String
   * @return org.github.spring.base.entity.OauthAccessTokenEntity
   */
  public OauthAccessTokenEntity withTokenId(String tokenId) {
    this.setTokenId(tokenId);
    return this;
  }

  /**
   * SET token_id [ oauth_access_token.token_id ].
   *
   * @param tokenId java.lang.String
   */
  public void setTokenId(String tokenId) {
    this.tokenId = tokenId == null ? null : tokenId.trim();
  }

  /**
   * GET authentication_id [ oauth_access_token.authentication_id ].
   *
   * @return java.lang.String
   */
  public String getAuthenticationId() {
    return authenticationId;
  }

  /**
   * WITH authentication_id [ oauth_access_token.authentication_id ].
   *
   * @param authenticationId java.lang.String
   * @return org.github.spring.base.entity.OauthAccessTokenEntity
   */
  public OauthAccessTokenEntity withAuthenticationId(String authenticationId) {
    this.setAuthenticationId(authenticationId);
    return this;
  }

  /**
   * SET authentication_id [ oauth_access_token.authentication_id ].
   *
   * @param authenticationId java.lang.String
   */
  public void setAuthenticationId(String authenticationId) {
    this.authenticationId = authenticationId == null ? null : authenticationId.trim();
  }

  /**
   * GET user_name [ oauth_access_token.user_name ].
   *
   * @return java.lang.String
   */
  public String getUserName() {
    return userName;
  }

  /**
   * WITH user_name [ oauth_access_token.user_name ].
   *
   * @param userName java.lang.String
   * @return org.github.spring.base.entity.OauthAccessTokenEntity
   */
  public OauthAccessTokenEntity withUserName(String userName) {
    this.setUserName(userName);
    return this;
  }

  /**
   * SET user_name [ oauth_access_token.user_name ].
   *
   * @param userName java.lang.String
   */
  public void setUserName(String userName) {
    this.userName = userName == null ? null : userName.trim();
  }

  /**
   * GET refresh_token [ oauth_access_token.refresh_token ].
   *
   * @return java.lang.String
   */
  public String getRefreshToken() {
    return refreshToken;
  }

  /**
   * WITH refresh_token [ oauth_access_token.refresh_token ].
   *
   * @param refreshToken java.lang.String
   * @return org.github.spring.base.entity.OauthAccessTokenEntity
   */
  public OauthAccessTokenEntity withRefreshToken(String refreshToken) {
    this.setRefreshToken(refreshToken);
    return this;
  }

  /**
   * SET refresh_token [ oauth_access_token.refresh_token ].
   *
   * @param refreshToken java.lang.String
   */
  public void setRefreshToken(String refreshToken) {
    this.refreshToken = refreshToken == null ? null : refreshToken.trim();
  }
}