//*****************************************************************************
// The file is automatically generated by the program, do not manually modify. 
//*****************************************************************************

package org.github.spring.base.entity;

import java.io.Serializable;
import lombok.EqualsAndHashCode;
import org.github.spring.base.key.OauthClientDetailsKey;

/**
 * OauthClientDetailsEntity [ sampledb.oauth_client_details ].
 *
 * @author MyBatisGenerator
 * @version 2017-09-21
 */
@EqualsAndHashCode(callSuper = true)
@SuppressWarnings("serial")
public class OauthClientDetailsEntity extends OauthClientDetailsKey implements Serializable {
  /** resource_ids [ oauth_client_details.resource_ids ]. */
  private String resourceIds;

  /** client_secret [ oauth_client_details.client_secret ]. */
  private String clientSecret;

  /** scope [ oauth_client_details.scope ]. */
  private String scope;

  /** authorized_grant_types [ oauth_client_details.authorized_grant_types ]. */
  private String authorizedGrantTypes;

  /** web_server_redirect_uri [ oauth_client_details.web_server_redirect_uri ]. */
  private String webServerRedirectUri;

  /** authorities [ oauth_client_details.authorities ]. */
  private String authorities;

  /** access_token_validity [ oauth_client_details.access_token_validity ]. */
  private Integer accessTokenValidity;

  /** refresh_token_validity [ oauth_client_details.refresh_token_validity ]. */
  private Integer refreshTokenValidity;

  /** additional_information [ oauth_client_details.additional_information ]. */
  private String additionalInformation;

  /** autoapprove [ oauth_client_details.autoapprove ]. */
  private String autoapprove;

  /**
   * GET resource_ids [ oauth_client_details.resource_ids ].
   *
   * @return java.lang.String
   */
  public String getResourceIds() {
    return resourceIds;
  }

  /**
   * WITH resource_ids [ oauth_client_details.resource_ids ].
   *
   * @param resourceIds java.lang.String
   * @return org.github.spring.base.entity.OauthClientDetailsEntity
   */
  public OauthClientDetailsEntity withResourceIds(String resourceIds) {
    this.setResourceIds(resourceIds);
    return this;
  }

  /**
   * SET resource_ids [ oauth_client_details.resource_ids ].
   *
   * @param resourceIds java.lang.String
   */
  public void setResourceIds(String resourceIds) {
    this.resourceIds = resourceIds == null ? null : resourceIds.trim();
  }

  /**
   * GET client_secret [ oauth_client_details.client_secret ].
   *
   * @return java.lang.String
   */
  public String getClientSecret() {
    return clientSecret;
  }

  /**
   * WITH client_secret [ oauth_client_details.client_secret ].
   *
   * @param clientSecret java.lang.String
   * @return org.github.spring.base.entity.OauthClientDetailsEntity
   */
  public OauthClientDetailsEntity withClientSecret(String clientSecret) {
    this.setClientSecret(clientSecret);
    return this;
  }

  /**
   * SET client_secret [ oauth_client_details.client_secret ].
   *
   * @param clientSecret java.lang.String
   */
  public void setClientSecret(String clientSecret) {
    this.clientSecret = clientSecret == null ? null : clientSecret.trim();
  }

  /**
   * GET scope [ oauth_client_details.scope ].
   *
   * @return java.lang.String
   */
  public String getScope() {
    return scope;
  }

  /**
   * WITH scope [ oauth_client_details.scope ].
   *
   * @param scope java.lang.String
   * @return org.github.spring.base.entity.OauthClientDetailsEntity
   */
  public OauthClientDetailsEntity withScope(String scope) {
    this.setScope(scope);
    return this;
  }

  /**
   * SET scope [ oauth_client_details.scope ].
   *
   * @param scope java.lang.String
   */
  public void setScope(String scope) {
    this.scope = scope == null ? null : scope.trim();
  }

  /**
   * GET authorized_grant_types [ oauth_client_details.authorized_grant_types ].
   *
   * @return java.lang.String
   */
  public String getAuthorizedGrantTypes() {
    return authorizedGrantTypes;
  }

  /**
   * WITH authorized_grant_types [ oauth_client_details.authorized_grant_types ].
   *
   * @param authorizedGrantTypes java.lang.String
   * @return org.github.spring.base.entity.OauthClientDetailsEntity
   */
  public OauthClientDetailsEntity withAuthorizedGrantTypes(String authorizedGrantTypes) {
    this.setAuthorizedGrantTypes(authorizedGrantTypes);
    return this;
  }

  /**
   * SET authorized_grant_types [ oauth_client_details.authorized_grant_types ].
   *
   * @param authorizedGrantTypes java.lang.String
   */
  public void setAuthorizedGrantTypes(String authorizedGrantTypes) {
    this.authorizedGrantTypes = authorizedGrantTypes == null ? null : authorizedGrantTypes.trim();
  }

  /**
   * GET web_server_redirect_uri [ oauth_client_details.web_server_redirect_uri ].
   *
   * @return java.lang.String
   */
  public String getWebServerRedirectUri() {
    return webServerRedirectUri;
  }

  /**
   * WITH web_server_redirect_uri [ oauth_client_details.web_server_redirect_uri ].
   *
   * @param webServerRedirectUri java.lang.String
   * @return org.github.spring.base.entity.OauthClientDetailsEntity
   */
  public OauthClientDetailsEntity withWebServerRedirectUri(String webServerRedirectUri) {
    this.setWebServerRedirectUri(webServerRedirectUri);
    return this;
  }

  /**
   * SET web_server_redirect_uri [ oauth_client_details.web_server_redirect_uri ].
   *
   * @param webServerRedirectUri java.lang.String
   */
  public void setWebServerRedirectUri(String webServerRedirectUri) {
    this.webServerRedirectUri = webServerRedirectUri == null ? null : webServerRedirectUri.trim();
  }

  /**
   * GET authorities [ oauth_client_details.authorities ].
   *
   * @return java.lang.String
   */
  public String getAuthorities() {
    return authorities;
  }

  /**
   * WITH authorities [ oauth_client_details.authorities ].
   *
   * @param authorities java.lang.String
   * @return org.github.spring.base.entity.OauthClientDetailsEntity
   */
  public OauthClientDetailsEntity withAuthorities(String authorities) {
    this.setAuthorities(authorities);
    return this;
  }

  /**
   * SET authorities [ oauth_client_details.authorities ].
   *
   * @param authorities java.lang.String
   */
  public void setAuthorities(String authorities) {
    this.authorities = authorities == null ? null : authorities.trim();
  }

  /**
   * GET access_token_validity [ oauth_client_details.access_token_validity ].
   *
   * @return java.lang.Integer
   */
  public Integer getAccessTokenValidity() {
    return accessTokenValidity;
  }

  /**
   * WITH access_token_validity [ oauth_client_details.access_token_validity ].
   *
   * @param accessTokenValidity java.lang.Integer
   * @return org.github.spring.base.entity.OauthClientDetailsEntity
   */
  public OauthClientDetailsEntity withAccessTokenValidity(Integer accessTokenValidity) {
    this.setAccessTokenValidity(accessTokenValidity);
    return this;
  }

  /**
   * SET access_token_validity [ oauth_client_details.access_token_validity ].
   *
   * @param accessTokenValidity java.lang.Integer
   */
  public void setAccessTokenValidity(Integer accessTokenValidity) {
    this.accessTokenValidity = accessTokenValidity;
  }

  /**
   * GET refresh_token_validity [ oauth_client_details.refresh_token_validity ].
   *
   * @return java.lang.Integer
   */
  public Integer getRefreshTokenValidity() {
    return refreshTokenValidity;
  }

  /**
   * WITH refresh_token_validity [ oauth_client_details.refresh_token_validity ].
   *
   * @param refreshTokenValidity java.lang.Integer
   * @return org.github.spring.base.entity.OauthClientDetailsEntity
   */
  public OauthClientDetailsEntity withRefreshTokenValidity(Integer refreshTokenValidity) {
    this.setRefreshTokenValidity(refreshTokenValidity);
    return this;
  }

  /**
   * SET refresh_token_validity [ oauth_client_details.refresh_token_validity ].
   *
   * @param refreshTokenValidity java.lang.Integer
   */
  public void setRefreshTokenValidity(Integer refreshTokenValidity) {
    this.refreshTokenValidity = refreshTokenValidity;
  }

  /**
   * GET additional_information [ oauth_client_details.additional_information ].
   *
   * @return java.lang.String
   */
  public String getAdditionalInformation() {
    return additionalInformation;
  }

  /**
   * WITH additional_information [ oauth_client_details.additional_information ].
   *
   * @param additionalInformation java.lang.String
   * @return org.github.spring.base.entity.OauthClientDetailsEntity
   */
  public OauthClientDetailsEntity withAdditionalInformation(String additionalInformation) {
    this.setAdditionalInformation(additionalInformation);
    return this;
  }

  /**
   * SET additional_information [ oauth_client_details.additional_information ].
   *
   * @param additionalInformation java.lang.String
   */
  public void setAdditionalInformation(String additionalInformation) {
    this.additionalInformation = additionalInformation == null ? null : additionalInformation.trim();
  }

  /**
   * GET autoapprove [ oauth_client_details.autoapprove ].
   *
   * @return java.lang.String
   */
  public String getAutoapprove() {
    return autoapprove;
  }

  /**
   * WITH autoapprove [ oauth_client_details.autoapprove ].
   *
   * @param autoapprove java.lang.String
   * @return org.github.spring.base.entity.OauthClientDetailsEntity
   */
  public OauthClientDetailsEntity withAutoapprove(String autoapprove) {
    this.setAutoapprove(autoapprove);
    return this;
  }

  /**
   * SET autoapprove [ oauth_client_details.autoapprove ].
   *
   * @param autoapprove java.lang.String
   */
  public void setAutoapprove(String autoapprove) {
    this.autoapprove = autoapprove == null ? null : autoapprove.trim();
  }
}