//*****************************************************************************
// The file is automatically generated by the program, do not manually modify. 
//*****************************************************************************

package org.github.spring.base.entity;

import java.io.Serializable;
import lombok.EqualsAndHashCode;
import org.github.spring.base.key.PhotoKey;

/**
 * PhotoEntity [ sampledb.photo ].
 *
 * @author MyBatisGenerator
 * @version 2017-10-14
 */
@EqualsAndHashCode(callSuper = true)
@SuppressWarnings("serial")
public class PhotoEntity extends PhotoKey implements Serializable {
  /** image [ photo.image ]. */
  private String image;

  /** note [ photo.note ]. */
  private String note;

  /** content [ photo.content ]. */
  private String content;

  /** type [ photo.type ]. */
  private String type;

  /** notice [ photo.notice ]. */
  private String notice;

  /** time [ photo.time ]. */
  private String time;

  /** album_id [ photo.album_id ]. */
  private Integer albumId;

  /**
   * GET image [ photo.image ].
   *
   * @return java.lang.String
   */
  public String getImage() {
    return image;
  }

  /**
   * WITH image [ photo.image ].
   *
   * @param image java.lang.String
   * @return org.github.spring.base.entity.PhotoEntity
   */
  public PhotoEntity withImage(String image) {
    this.setImage(image);
    return this;
  }

  /**
   * SET image [ photo.image ].
   *
   * @param image java.lang.String
   */
  public void setImage(String image) {
    this.image = image == null ? null : image.trim();
  }

  /**
   * GET note [ photo.note ].
   *
   * @return java.lang.String
   */
  public String getNote() {
    return note;
  }

  /**
   * WITH note [ photo.note ].
   *
   * @param note java.lang.String
   * @return org.github.spring.base.entity.PhotoEntity
   */
  public PhotoEntity withNote(String note) {
    this.setNote(note);
    return this;
  }

  /**
   * SET note [ photo.note ].
   *
   * @param note java.lang.String
   */
  public void setNote(String note) {
    this.note = note == null ? null : note.trim();
  }

  /**
   * GET content [ photo.content ].
   *
   * @return java.lang.String
   */
  public String getContent() {
    return content;
  }

  /**
   * WITH content [ photo.content ].
   *
   * @param content java.lang.String
   * @return org.github.spring.base.entity.PhotoEntity
   */
  public PhotoEntity withContent(String content) {
    this.setContent(content);
    return this;
  }

  /**
   * SET content [ photo.content ].
   *
   * @param content java.lang.String
   */
  public void setContent(String content) {
    this.content = content == null ? null : content.trim();
  }

  /**
   * GET type [ photo.type ].
   *
   * @return java.lang.String
   */
  public String getType() {
    return type;
  }

  /**
   * WITH type [ photo.type ].
   *
   * @param type java.lang.String
   * @return org.github.spring.base.entity.PhotoEntity
   */
  public PhotoEntity withType(String type) {
    this.setType(type);
    return this;
  }

  /**
   * SET type [ photo.type ].
   *
   * @param type java.lang.String
   */
  public void setType(String type) {
    this.type = type == null ? null : type.trim();
  }

  /**
   * GET notice [ photo.notice ].
   *
   * @return java.lang.String
   */
  public String getNotice() {
    return notice;
  }

  /**
   * WITH notice [ photo.notice ].
   *
   * @param notice java.lang.String
   * @return org.github.spring.base.entity.PhotoEntity
   */
  public PhotoEntity withNotice(String notice) {
    this.setNotice(notice);
    return this;
  }

  /**
   * SET notice [ photo.notice ].
   *
   * @param notice java.lang.String
   */
  public void setNotice(String notice) {
    this.notice = notice == null ? null : notice.trim();
  }

  /**
   * GET time [ photo.time ].
   *
   * @return java.lang.String
   */
  public String getTime() {
    return time;
  }

  /**
   * WITH time [ photo.time ].
   *
   * @param time java.lang.String
   * @return org.github.spring.base.entity.PhotoEntity
   */
  public PhotoEntity withTime(String time) {
    this.setTime(time);
    return this;
  }

  /**
   * SET time [ photo.time ].
   *
   * @param time java.lang.String
   */
  public void setTime(String time) {
    this.time = time == null ? null : time.trim();
  }

  /**
   * GET album_id [ photo.album_id ].
   *
   * @return java.lang.Integer
   */
  public Integer getAlbumId() {
    return albumId;
  }

  /**
   * WITH album_id [ photo.album_id ].
   *
   * @param albumId java.lang.Integer
   * @return org.github.spring.base.entity.PhotoEntity
   */
  public PhotoEntity withAlbumId(Integer albumId) {
    this.setAlbumId(albumId);
    return this;
  }

  /**
   * SET album_id [ photo.album_id ].
   *
   * @param albumId java.lang.Integer
   */
  public void setAlbumId(Integer albumId) {
    this.albumId = albumId;
  }
}