//*****************************************************************************
// The file is automatically generated by the program, do not manually modify. 
//*****************************************************************************

package org.github.spring.base.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.EqualsAndHashCode;
import org.github.spring.base.key.SourceKey;

/**
 * SourceEntity [ sampledb.t_source ].
 *
 * @author MyBatisGenerator
 * @version 2017-10-14
 */
@EqualsAndHashCode(callSuper = true)
@SuppressWarnings("serial")
public class SourceEntity extends SourceKey implements Serializable {
  /** 用户ID（外键） [ t_source.user_id ]. */
  private String userId;

  /** 标题 [ t_source.title ]. */
  private String title;

  /** 类型 [ t_source.type ]. */
  private String type;

  /** 描述信息 [ t_source.sdecotation ]. */
  private String sdecotation;

  /** 资源下载地址 [ t_source.source_url ]. */
  private String sourceUrl;

  /** 创建时间 [ t_source.create_time ]. */
  private Date createTime;

  /**
   * GET 用户ID（外键） [ t_source.user_id ].
   *
   * @return java.lang.String
   */
  public String getUserId() {
    return userId;
  }

  /**
   * WITH 用户ID（外键） [ t_source.user_id ].
   *
   * @param userId java.lang.String
   * @return org.github.spring.base.entity.SourceEntity
   */
  public SourceEntity withUserId(String userId) {
    this.setUserId(userId);
    return this;
  }

  /**
   * SET 用户ID（外键） [ t_source.user_id ].
   *
   * @param userId java.lang.String
   */
  public void setUserId(String userId) {
    this.userId = userId == null ? null : userId.trim();
  }

  /**
   * GET 标题 [ t_source.title ].
   *
   * @return java.lang.String
   */
  public String getTitle() {
    return title;
  }

  /**
   * WITH 标题 [ t_source.title ].
   *
   * @param title java.lang.String
   * @return org.github.spring.base.entity.SourceEntity
   */
  public SourceEntity withTitle(String title) {
    this.setTitle(title);
    return this;
  }

  /**
   * SET 标题 [ t_source.title ].
   *
   * @param title java.lang.String
   */
  public void setTitle(String title) {
    this.title = title == null ? null : title.trim();
  }

  /**
   * GET 类型 [ t_source.type ].
   *
   * @return java.lang.String
   */
  public String getType() {
    return type;
  }

  /**
   * WITH 类型 [ t_source.type ].
   *
   * @param type java.lang.String
   * @return org.github.spring.base.entity.SourceEntity
   */
  public SourceEntity withType(String type) {
    this.setType(type);
    return this;
  }

  /**
   * SET 类型 [ t_source.type ].
   *
   * @param type java.lang.String
   */
  public void setType(String type) {
    this.type = type == null ? null : type.trim();
  }

  /**
   * GET 描述信息 [ t_source.sdecotation ].
   *
   * @return java.lang.String
   */
  public String getSdecotation() {
    return sdecotation;
  }

  /**
   * WITH 描述信息 [ t_source.sdecotation ].
   *
   * @param sdecotation java.lang.String
   * @return org.github.spring.base.entity.SourceEntity
   */
  public SourceEntity withSdecotation(String sdecotation) {
    this.setSdecotation(sdecotation);
    return this;
  }

  /**
   * SET 描述信息 [ t_source.sdecotation ].
   *
   * @param sdecotation java.lang.String
   */
  public void setSdecotation(String sdecotation) {
    this.sdecotation = sdecotation == null ? null : sdecotation.trim();
  }

  /**
   * GET 资源下载地址 [ t_source.source_url ].
   *
   * @return java.lang.String
   */
  public String getSourceUrl() {
    return sourceUrl;
  }

  /**
   * WITH 资源下载地址 [ t_source.source_url ].
   *
   * @param sourceUrl java.lang.String
   * @return org.github.spring.base.entity.SourceEntity
   */
  public SourceEntity withSourceUrl(String sourceUrl) {
    this.setSourceUrl(sourceUrl);
    return this;
  }

  /**
   * SET 资源下载地址 [ t_source.source_url ].
   *
   * @param sourceUrl java.lang.String
   */
  public void setSourceUrl(String sourceUrl) {
    this.sourceUrl = sourceUrl == null ? null : sourceUrl.trim();
  }

  /**
   * GET 创建时间 [ t_source.create_time ].
   *
   * @return java.util.Date
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * WITH 创建时间 [ t_source.create_time ].
   *
   * @param createTime java.util.Date
   * @return org.github.spring.base.entity.SourceEntity
   */
  public SourceEntity withCreateTime(Date createTime) {
    this.setCreateTime(createTime);
    return this;
  }

  /**
   * SET 创建时间 [ t_source.create_time ].
   *
   * @param createTime java.util.Date
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }
}