//*****************************************************************************
// The file is automatically generated by the program, do not manually modify. 
//*****************************************************************************

package org.github.spring.base.entity;

import java.io.Serializable;
import lombok.EqualsAndHashCode;
import org.github.spring.base.key.UsersInfoKey;

/**
 * UsersInfoEntity [ sampledb.t_users_info ].
 *
 * @author MyBatisGenerator
 * @version 2017-10-14
 */
@EqualsAndHashCode(callSuper = true)
@SuppressWarnings("serial")
public class UsersInfoEntity extends UsersInfoKey implements Serializable {
  /** 用户姓名 [ t_users_info.name ]. */
  private String name;

  /** 用户性别('0','1')('男','女') [ t_users_info.sex ]. */
  private String sex;

  /** 生日 [ t_users_info.birthday ]. */
  private String birthday;

  /** 邮箱 [ t_users_info.email ]. */
  private String email;

  /** 电话 [ t_users_info.tel_phone ]. */
  private String telPhone;

  /**
   * GET 用户姓名 [ t_users_info.name ].
   *
   * @return java.lang.String
   */
  public String getName() {
    return name;
  }

  /**
   * WITH 用户姓名 [ t_users_info.name ].
   *
   * @param name java.lang.String
   * @return org.github.spring.base.entity.UsersInfoEntity
   */
  public UsersInfoEntity withName(String name) {
    this.setName(name);
    return this;
  }

  /**
   * SET 用户姓名 [ t_users_info.name ].
   *
   * @param name java.lang.String
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }

  /**
   * GET 用户性别('0','1')('男','女') [ t_users_info.sex ].
   *
   * @return java.lang.String
   */
  public String getSex() {
    return sex;
  }

  /**
   * WITH 用户性别('0','1')('男','女') [ t_users_info.sex ].
   *
   * @param sex java.lang.String
   * @return org.github.spring.base.entity.UsersInfoEntity
   */
  public UsersInfoEntity withSex(String sex) {
    this.setSex(sex);
    return this;
  }

  /**
   * SET 用户性别('0','1')('男','女') [ t_users_info.sex ].
   *
   * @param sex java.lang.String
   */
  public void setSex(String sex) {
    this.sex = sex == null ? null : sex.trim();
  }

  /**
   * GET 生日 [ t_users_info.birthday ].
   *
   * @return java.lang.String
   */
  public String getBirthday() {
    return birthday;
  }

  /**
   * WITH 生日 [ t_users_info.birthday ].
   *
   * @param birthday java.lang.String
   * @return org.github.spring.base.entity.UsersInfoEntity
   */
  public UsersInfoEntity withBirthday(String birthday) {
    this.setBirthday(birthday);
    return this;
  }

  /**
   * SET 生日 [ t_users_info.birthday ].
   *
   * @param birthday java.lang.String
   */
  public void setBirthday(String birthday) {
    this.birthday = birthday == null ? null : birthday.trim();
  }

  /**
   * GET 邮箱 [ t_users_info.email ].
   *
   * @return java.lang.String
   */
  public String getEmail() {
    return email;
  }

  /**
   * WITH 邮箱 [ t_users_info.email ].
   *
   * @param email java.lang.String
   * @return org.github.spring.base.entity.UsersInfoEntity
   */
  public UsersInfoEntity withEmail(String email) {
    this.setEmail(email);
    return this;
  }

  /**
   * SET 邮箱 [ t_users_info.email ].
   *
   * @param email java.lang.String
   */
  public void setEmail(String email) {
    this.email = email == null ? null : email.trim();
  }

  /**
   * GET 电话 [ t_users_info.tel_phone ].
   *
   * @return java.lang.String
   */
  public String getTelPhone() {
    return telPhone;
  }

  /**
   * WITH 电话 [ t_users_info.tel_phone ].
   *
   * @param telPhone java.lang.String
   * @return org.github.spring.base.entity.UsersInfoEntity
   */
  public UsersInfoEntity withTelPhone(String telPhone) {
    this.setTelPhone(telPhone);
    return this;
  }

  /**
   * SET 电话 [ t_users_info.tel_phone ].
   *
   * @param telPhone java.lang.String
   */
  public void setTelPhone(String telPhone) {
    this.telPhone = telPhone == null ? null : telPhone.trim();
  }
}