//*****************************************************************************
// The file is automatically generated by the program, do not manually modify. 
//*****************************************************************************

package org.github.spring.base.key;

import java.io.Serializable;
import lombok.EqualsAndHashCode;
import org.github.spring.footstone.AbstractEntity;

/**
 * ArtStatKey [ sampledb.t_art_stat ].
 *
 * @author MyBatisGenerator
 * @version 2017-10-14
 */
@EqualsAndHashCode(callSuper = true)
@SuppressWarnings("serial")
public class ArtStatKey extends AbstractEntity implements Serializable {
  /** 文章ID（主键、外键） [ t_art_stat.tid ]. */
  private String tid;

  /**
   * GET 文章ID（主键、外键） [ t_art_stat.tid ].
   *
   * @return java.lang.String
   */
  public String getTid() {
    return tid;
  }

  /**
   * WITH 文章ID（主键、外键） [ t_art_stat.tid ].
   *
   * @param tid java.lang.String
   * @return org.github.spring.base.key.ArtStatKey
   */
  public ArtStatKey withTid(String tid) {
    this.setTid(tid);
    return this;
  }

  /**
   * SET 文章ID（主键、外键） [ t_art_stat.tid ].
   *
   * @param tid java.lang.String
   */
  public void setTid(String tid) {
    this.tid = tid == null ? null : tid.trim();
  }
}