//*****************************************************************************
// The file is automatically generated by the program, do not manually modify. 
//*****************************************************************************

package org.github.spring.base.key;

import java.io.Serializable;
import lombok.EqualsAndHashCode;
import org.github.spring.footstone.AbstractEntity;

/**
 * BlogKey [ sampledb.t_blog ].
 *
 * @author MyBatisGenerator
 * @version 2017-09-21
 */
@EqualsAndHashCode(callSuper = true)
@SuppressWarnings("serial")
public class BlogKey extends AbstractEntity implements Serializable {
  /** 文章ID（主键） [ t_blog.tid ]. */
  private String tid;

  /**
   * GET 文章ID（主键） [ t_blog.tid ].
   *
   * @return java.lang.String
   */
  public String getTid() {
    return tid;
  }

  /**
   * WITH 文章ID（主键） [ t_blog.tid ].
   *
   * @param tid java.lang.String
   * @return org.github.spring.base.key.BlogKey
   */
  public BlogKey withTid(String tid) {
    this.setTid(tid);
    return this;
  }

  /**
   * SET 文章ID（主键） [ t_blog.tid ].
   *
   * @param tid java.lang.String
   */
  public void setTid(String tid) {
    this.tid = tid == null ? null : tid.trim();
  }
}