//*****************************************************************************
// The file is automatically generated by the program, do not manually modify. 
//*****************************************************************************

package org.github.spring.base.key;

import java.io.Serializable;
import lombok.EqualsAndHashCode;
import org.github.spring.footstone.AbstractEntity;

/**
 * MeKey [ sampledb.me ].
 *
 * @author MyBatisGenerator
 * @version 2017-10-14
 */
@EqualsAndHashCode(callSuper = true)
@SuppressWarnings("serial")
public class MeKey extends AbstractEntity implements Serializable {
  /** id [ me.id ]. */
  private Integer id;

  /**
   * GET id [ me.id ].
   *
   * @return java.lang.Integer
   */
  public Integer getId() {
    return id;
  }

  /**
   * WITH id [ me.id ].
   *
   * @param id java.lang.Integer
   * @return org.github.spring.base.key.MeKey
   */
  public MeKey withId(Integer id) {
    this.setId(id);
    return this;
  }

  /**
   * SET id [ me.id ].
   *
   * @param id java.lang.Integer
   */
  public void setId(Integer id) {
    this.id = id;
  }
}