//*****************************************************************************
// The file is automatically generated by the program, do not manually modify. 
//*****************************************************************************

package org.github.spring.base.key;

import java.io.Serializable;
import lombok.EqualsAndHashCode;
import org.github.spring.footstone.AbstractEntity;

/**
 * OauthClientDetailsKey [ sampledb.oauth_client_details ].
 *
 * @author MyBatisGenerator
 * @version 2017-09-21
 */
@EqualsAndHashCode(callSuper = true)
@SuppressWarnings("serial")
public class OauthClientDetailsKey extends AbstractEntity implements Serializable {
  /** client_id [ oauth_client_details.client_id ]. */
  private String clientId;

  /**
   * GET client_id [ oauth_client_details.client_id ].
   *
   * @return java.lang.String
   */
  public String getClientId() {
    return clientId;
  }

  /**
   * WITH client_id [ oauth_client_details.client_id ].
   *
   * @param clientId java.lang.String
   * @return org.github.spring.base.key.OauthClientDetailsKey
   */
  public OauthClientDetailsKey withClientId(String clientId) {
    this.setClientId(clientId);
    return this;
  }

  /**
   * SET client_id [ oauth_client_details.client_id ].
   *
   * @param clientId java.lang.String
   */
  public void setClientId(String clientId) {
    this.clientId = clientId == null ? null : clientId.trim();
  }
}