//*****************************************************************************
// The file is automatically generated by the program, do not manually modify. 
//*****************************************************************************

package org.github.spring.base.key;

import java.io.Serializable;
import lombok.EqualsAndHashCode;
import org.github.spring.footstone.AbstractEntity;

/**
 * OauthClientTokenKey [ sampledb.oauth_client_token ].
 *
 * @author MyBatisGenerator
 * @version 2017-09-21
 */
@EqualsAndHashCode(callSuper = true)
@SuppressWarnings("serial")
public class OauthClientTokenKey extends AbstractEntity implements Serializable {
  /** token_id [ oauth_client_token.token_id ]. */
  private String tokenId;

  /**
   * GET token_id [ oauth_client_token.token_id ].
   *
   * @return java.lang.String
   */
  public String getTokenId() {
    return tokenId;
  }

  /**
   * WITH token_id [ oauth_client_token.token_id ].
   *
   * @param tokenId java.lang.String
   * @return org.github.spring.base.key.OauthClientTokenKey
   */
  public OauthClientTokenKey withTokenId(String tokenId) {
    this.setTokenId(tokenId);
    return this;
  }

  /**
   * SET token_id [ oauth_client_token.token_id ].
   *
   * @param tokenId java.lang.String
   */
  public void setTokenId(String tokenId) {
    this.tokenId = tokenId == null ? null : tokenId.trim();
  }
}