//*****************************************************************************
// The file is automatically generated by the program, do not manually modify. 
//*****************************************************************************

package org.github.spring.base.key;

import java.io.Serializable;
import lombok.EqualsAndHashCode;
import org.github.spring.footstone.AbstractEntity;

/**
 * ResponseOneKey [ sampledb.t_response_one ].
 *
 * @author MyBatisGenerator
 * @version 2017-10-14
 */
@EqualsAndHashCode(callSuper = true)
@SuppressWarnings("serial")
public class ResponseOneKey extends AbstractEntity implements Serializable {
  /** 回复ID（主键） [ t_response_one.post_id ]. */
  private String postId;

  /**
   * GET 回复ID（主键） [ t_response_one.post_id ].
   *
   * @return java.lang.String
   */
  public String getPostId() {
    return postId;
  }

  /**
   * WITH 回复ID（主键） [ t_response_one.post_id ].
   *
   * @param postId java.lang.String
   * @return org.github.spring.base.key.ResponseOneKey
   */
  public ResponseOneKey withPostId(String postId) {
    this.setPostId(postId);
    return this;
  }

  /**
   * SET 回复ID（主键） [ t_response_one.post_id ].
   *
   * @param postId java.lang.String
   */
  public void setPostId(String postId) {
    this.postId = postId == null ? null : postId.trim();
  }
}