//*****************************************************************************
// The file is automatically generated by the program, do not manually modify. 
//*****************************************************************************

package org.github.spring.base.key;

import java.io.Serializable;
import lombok.EqualsAndHashCode;
import org.github.spring.footstone.AbstractEntity;

/**
 * UsersInfoKey [ sampledb.t_users_info ].
 *
 * @author MyBatisGenerator
 * @version 2017-10-14
 */
@EqualsAndHashCode(callSuper = true)
@SuppressWarnings("serial")
public class UsersInfoKey extends AbstractEntity implements Serializable {
  /** 用户ID（主键+外键） [ t_users_info.user_id ]. */
  private String userId;

  /**
   * GET 用户ID（主键+外键） [ t_users_info.user_id ].
   *
   * @return java.lang.String
   */
  public String getUserId() {
    return userId;
  }

  /**
   * WITH 用户ID（主键+外键） [ t_users_info.user_id ].
   *
   * @param userId java.lang.String
   * @return org.github.spring.base.key.UsersInfoKey
   */
  public UsersInfoKey withUserId(String userId) {
    this.setUserId(userId);
    return this;
  }

  /**
   * SET 用户ID（主键+外键） [ t_users_info.user_id ].
   *
   * @param userId java.lang.String
   */
  public void setUserId(String userId) {
    this.userId = userId == null ? null : userId.trim();
  }
}