//*****************************************************************************
// The file is automatically generated by the program, do not manually modify. 
//*****************************************************************************

package org.github.spring.base.blob;

import java.io.Serializable;
import lombok.EqualsAndHashCode;
import org.github.spring.base.entity.OauthClientTokenEntity;

/**
 * OauthClientTokenWithBLOBs [ sampledb.oauth_client_token ].
 *
 * @author MyBatisGenerator
 * @version 2017-09-21
 */
@EqualsAndHashCode(callSuper = true)
@SuppressWarnings("serial")
public class OauthClientTokenWithBLOBs extends OauthClientTokenEntity implements Serializable {
  /** token [ oauth_client_token.token ]. */
  private byte[] token;

  /**
   * GET token [ oauth_client_token.token ].
   *
   * @return byte[]
   */
  public byte[] getToken() {
    return token;
  }

  /**
   * WITH token [ oauth_client_token.token ].
   *
   * @param token byte[]
   * @return org.github.spring.base.blob.OauthClientTokenWithBLOBs
   */
  public OauthClientTokenWithBLOBs withToken(byte[] token) {
    this.setToken(token);
    return this;
  }

  /**
   * SET token [ oauth_client_token.token ].
   *
   * @param token byte[]
   */
  public void setToken(byte[] token) {
    this.token = token;
  }
}