//*****************************************************************************
// The file is automatically generated by the program, do not manually modify. 
//*****************************************************************************

package org.github.spring.base.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BlogExample {
  protected String orderByClause;

  protected boolean distinct;

  protected List<Criteria> oredCriteria;

  public BlogExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  public String getOrderByClause() {
    return orderByClause;
  }

  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  public boolean isDistinct() {
    return distinct;
  }

  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria(this);
    return criteria;
  }

  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andTidIsNull() {
      addCriterion("tid is null");
      return (Criteria) this;
    }

    public Criteria andTidIsNotNull() {
      addCriterion("tid is not null");
      return (Criteria) this;
    }

    public Criteria andTidEqualTo(String value) {
      if(value != null) addCriterion("tid =", value, "tid");
      return (Criteria) this;
    }

    public Criteria andTidNotEqualTo(String value) {
      if(value != null) addCriterion("tid <>", value, "tid");
      return (Criteria) this;
    }

    public Criteria andTidGreaterThan(String value) {
      if(value != null) addCriterion("tid >", value, "tid");
      return (Criteria) this;
    }

    public Criteria andTidGreaterThanOrEqualTo(String value) {
      if(value != null) addCriterion("tid >=", value, "tid");
      return (Criteria) this;
    }

    public Criteria andTidLessThan(String value) {
      if(value != null) addCriterion("tid <", value, "tid");
      return (Criteria) this;
    }

    public Criteria andTidLessThanOrEqualTo(String value) {
      if(value != null) addCriterion("tid <=", value, "tid");
      return (Criteria) this;
    }

    public Criteria andTidLike(String value) {
      if(value != null) addCriterion("tid like", value, "tid");
      return (Criteria) this;
    }

    public Criteria andTidNotLike(String value) {
      if(value != null) addCriterion("tid not like", value, "tid");
      return (Criteria) this;
    }

    public Criteria andTidIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("tid in", values, "tid");
      return (Criteria) this;
    }

    public Criteria andTidNotIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("tid not in", values, "tid");
      return (Criteria) this;
    }

    public Criteria andTidBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("tid between", head, tail, "tid");
      return (Criteria) this;
    }

    public Criteria andTidNotBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("tid not between", head, tail, "tid");
      return (Criteria) this;
    }

    public Criteria andUserIdIsNull() {
      addCriterion("user_id is null");
      return (Criteria) this;
    }

    public Criteria andUserIdIsNotNull() {
      addCriterion("user_id is not null");
      return (Criteria) this;
    }

    public Criteria andUserIdEqualTo(String value) {
      if(value != null) addCriterion("user_id =", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdNotEqualTo(String value) {
      if(value != null) addCriterion("user_id <>", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdGreaterThan(String value) {
      if(value != null) addCriterion("user_id >", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdGreaterThanOrEqualTo(String value) {
      if(value != null) addCriterion("user_id >=", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdLessThan(String value) {
      if(value != null) addCriterion("user_id <", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdLessThanOrEqualTo(String value) {
      if(value != null) addCriterion("user_id <=", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdLike(String value) {
      if(value != null) addCriterion("user_id like", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdNotLike(String value) {
      if(value != null) addCriterion("user_id not like", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("user_id in", values, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdNotIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("user_id not in", values, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("user_id between", head, tail, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdNotBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("user_id not between", head, tail, "userId");
      return (Criteria) this;
    }

    public Criteria andTitleIsNull() {
      addCriterion("title is null");
      return (Criteria) this;
    }

    public Criteria andTitleIsNotNull() {
      addCriterion("title is not null");
      return (Criteria) this;
    }

    public Criteria andTitleEqualTo(String value) {
      if(value != null) addCriterion("title =", value, "title");
      return (Criteria) this;
    }

    public Criteria andTitleNotEqualTo(String value) {
      if(value != null) addCriterion("title <>", value, "title");
      return (Criteria) this;
    }

    public Criteria andTitleGreaterThan(String value) {
      if(value != null) addCriterion("title >", value, "title");
      return (Criteria) this;
    }

    public Criteria andTitleGreaterThanOrEqualTo(String value) {
      if(value != null) addCriterion("title >=", value, "title");
      return (Criteria) this;
    }

    public Criteria andTitleLessThan(String value) {
      if(value != null) addCriterion("title <", value, "title");
      return (Criteria) this;
    }

    public Criteria andTitleLessThanOrEqualTo(String value) {
      if(value != null) addCriterion("title <=", value, "title");
      return (Criteria) this;
    }

    public Criteria andTitleLike(String value) {
      if(value != null) addCriterion("title like", value, "title");
      return (Criteria) this;
    }

    public Criteria andTitleNotLike(String value) {
      if(value != null) addCriterion("title not like", value, "title");
      return (Criteria) this;
    }

    public Criteria andTitleIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("title in", values, "title");
      return (Criteria) this;
    }

    public Criteria andTitleNotIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("title not in", values, "title");
      return (Criteria) this;
    }

    public Criteria andTitleBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("title between", head, tail, "title");
      return (Criteria) this;
    }

    public Criteria andTitleNotBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("title not between", head, tail, "title");
      return (Criteria) this;
    }

    public Criteria andAuthorIsNull() {
      addCriterion("author is null");
      return (Criteria) this;
    }

    public Criteria andAuthorIsNotNull() {
      addCriterion("author is not null");
      return (Criteria) this;
    }

    public Criteria andAuthorEqualTo(String value) {
      if(value != null) addCriterion("author =", value, "author");
      return (Criteria) this;
    }

    public Criteria andAuthorNotEqualTo(String value) {
      if(value != null) addCriterion("author <>", value, "author");
      return (Criteria) this;
    }

    public Criteria andAuthorGreaterThan(String value) {
      if(value != null) addCriterion("author >", value, "author");
      return (Criteria) this;
    }

    public Criteria andAuthorGreaterThanOrEqualTo(String value) {
      if(value != null) addCriterion("author >=", value, "author");
      return (Criteria) this;
    }

    public Criteria andAuthorLessThan(String value) {
      if(value != null) addCriterion("author <", value, "author");
      return (Criteria) this;
    }

    public Criteria andAuthorLessThanOrEqualTo(String value) {
      if(value != null) addCriterion("author <=", value, "author");
      return (Criteria) this;
    }

    public Criteria andAuthorLike(String value) {
      if(value != null) addCriterion("author like", value, "author");
      return (Criteria) this;
    }

    public Criteria andAuthorNotLike(String value) {
      if(value != null) addCriterion("author not like", value, "author");
      return (Criteria) this;
    }

    public Criteria andAuthorIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("author in", values, "author");
      return (Criteria) this;
    }

    public Criteria andAuthorNotIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("author not in", values, "author");
      return (Criteria) this;
    }

    public Criteria andAuthorBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("author between", head, tail, "author");
      return (Criteria) this;
    }

    public Criteria andAuthorNotBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("author not between", head, tail, "author");
      return (Criteria) this;
    }

    public Criteria andTypeIsNull() {
      addCriterion("`type` is null");
      return (Criteria) this;
    }

    public Criteria andTypeIsNotNull() {
      addCriterion("`type` is not null");
      return (Criteria) this;
    }

    public Criteria andTypeEqualTo(String value) {
      if(value != null) addCriterion("`type` =", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeNotEqualTo(String value) {
      if(value != null) addCriterion("`type` <>", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeGreaterThan(String value) {
      if(value != null) addCriterion("`type` >", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeGreaterThanOrEqualTo(String value) {
      if(value != null) addCriterion("`type` >=", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeLessThan(String value) {
      if(value != null) addCriterion("`type` <", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeLessThanOrEqualTo(String value) {
      if(value != null) addCriterion("`type` <=", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeLike(String value) {
      if(value != null) addCriterion("`type` like", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeNotLike(String value) {
      if(value != null) addCriterion("`type` not like", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("`type` in", values, "type");
      return (Criteria) this;
    }

    public Criteria andTypeNotIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("`type` not in", values, "type");
      return (Criteria) this;
    }

    public Criteria andTypeBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("`type` between", head, tail, "type");
      return (Criteria) this;
    }

    public Criteria andTypeNotBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("`type` not between", head, tail, "type");
      return (Criteria) this;
    }

    public Criteria andLoadurlIsNull() {
      addCriterion("loadURL is null");
      return (Criteria) this;
    }

    public Criteria andLoadurlIsNotNull() {
      addCriterion("loadURL is not null");
      return (Criteria) this;
    }

    public Criteria andLoadurlEqualTo(String value) {
      if(value != null) addCriterion("loadURL =", value, "loadurl");
      return (Criteria) this;
    }

    public Criteria andLoadurlNotEqualTo(String value) {
      if(value != null) addCriterion("loadURL <>", value, "loadurl");
      return (Criteria) this;
    }

    public Criteria andLoadurlGreaterThan(String value) {
      if(value != null) addCriterion("loadURL >", value, "loadurl");
      return (Criteria) this;
    }

    public Criteria andLoadurlGreaterThanOrEqualTo(String value) {
      if(value != null) addCriterion("loadURL >=", value, "loadurl");
      return (Criteria) this;
    }

    public Criteria andLoadurlLessThan(String value) {
      if(value != null) addCriterion("loadURL <", value, "loadurl");
      return (Criteria) this;
    }

    public Criteria andLoadurlLessThanOrEqualTo(String value) {
      if(value != null) addCriterion("loadURL <=", value, "loadurl");
      return (Criteria) this;
    }

    public Criteria andLoadurlLike(String value) {
      if(value != null) addCriterion("loadURL like", value, "loadurl");
      return (Criteria) this;
    }

    public Criteria andLoadurlNotLike(String value) {
      if(value != null) addCriterion("loadURL not like", value, "loadurl");
      return (Criteria) this;
    }

    public Criteria andLoadurlIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("loadURL in", values, "loadurl");
      return (Criteria) this;
    }

    public Criteria andLoadurlNotIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("loadURL not in", values, "loadurl");
      return (Criteria) this;
    }

    public Criteria andLoadurlBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("loadURL between", head, tail, "loadurl");
      return (Criteria) this;
    }

    public Criteria andLoadurlNotBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("loadURL not between", head, tail, "loadurl");
      return (Criteria) this;
    }

    public Criteria andLabelIsNull() {
      addCriterion("`label` is null");
      return (Criteria) this;
    }

    public Criteria andLabelIsNotNull() {
      addCriterion("`label` is not null");
      return (Criteria) this;
    }

    public Criteria andLabelEqualTo(String value) {
      if(value != null) addCriterion("`label` =", value, "label");
      return (Criteria) this;
    }

    public Criteria andLabelNotEqualTo(String value) {
      if(value != null) addCriterion("`label` <>", value, "label");
      return (Criteria) this;
    }

    public Criteria andLabelGreaterThan(String value) {
      if(value != null) addCriterion("`label` >", value, "label");
      return (Criteria) this;
    }

    public Criteria andLabelGreaterThanOrEqualTo(String value) {
      if(value != null) addCriterion("`label` >=", value, "label");
      return (Criteria) this;
    }

    public Criteria andLabelLessThan(String value) {
      if(value != null) addCriterion("`label` <", value, "label");
      return (Criteria) this;
    }

    public Criteria andLabelLessThanOrEqualTo(String value) {
      if(value != null) addCriterion("`label` <=", value, "label");
      return (Criteria) this;
    }

    public Criteria andLabelLike(String value) {
      if(value != null) addCriterion("`label` like", value, "label");
      return (Criteria) this;
    }

    public Criteria andLabelNotLike(String value) {
      if(value != null) addCriterion("`label` not like", value, "label");
      return (Criteria) this;
    }

    public Criteria andLabelIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("`label` in", values, "label");
      return (Criteria) this;
    }

    public Criteria andLabelNotIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("`label` not in", values, "label");
      return (Criteria) this;
    }

    public Criteria andLabelBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("`label` between", head, tail, "label");
      return (Criteria) this;
    }

    public Criteria andLabelNotBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("`label` not between", head, tail, "label");
      return (Criteria) this;
    }

    public Criteria andDecorationIsNull() {
      addCriterion("decoration is null");
      return (Criteria) this;
    }

    public Criteria andDecorationIsNotNull() {
      addCriterion("decoration is not null");
      return (Criteria) this;
    }

    public Criteria andDecorationEqualTo(String value) {
      if(value != null) addCriterion("decoration =", value, "decoration");
      return (Criteria) this;
    }

    public Criteria andDecorationNotEqualTo(String value) {
      if(value != null) addCriterion("decoration <>", value, "decoration");
      return (Criteria) this;
    }

    public Criteria andDecorationGreaterThan(String value) {
      if(value != null) addCriterion("decoration >", value, "decoration");
      return (Criteria) this;
    }

    public Criteria andDecorationGreaterThanOrEqualTo(String value) {
      if(value != null) addCriterion("decoration >=", value, "decoration");
      return (Criteria) this;
    }

    public Criteria andDecorationLessThan(String value) {
      if(value != null) addCriterion("decoration <", value, "decoration");
      return (Criteria) this;
    }

    public Criteria andDecorationLessThanOrEqualTo(String value) {
      if(value != null) addCriterion("decoration <=", value, "decoration");
      return (Criteria) this;
    }

    public Criteria andDecorationLike(String value) {
      if(value != null) addCriterion("decoration like", value, "decoration");
      return (Criteria) this;
    }

    public Criteria andDecorationNotLike(String value) {
      if(value != null) addCriterion("decoration not like", value, "decoration");
      return (Criteria) this;
    }

    public Criteria andDecorationIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("decoration in", values, "decoration");
      return (Criteria) this;
    }

    public Criteria andDecorationNotIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("decoration not in", values, "decoration");
      return (Criteria) this;
    }

    public Criteria andDecorationBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("decoration between", head, tail, "decoration");
      return (Criteria) this;
    }

    public Criteria andDecorationNotBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("decoration not between", head, tail, "decoration");
      return (Criteria) this;
    }

    public Criteria andCreateTimeIsNull() {
      addCriterion("create_time is null");
      return (Criteria) this;
    }

    public Criteria andCreateTimeIsNotNull() {
      addCriterion("create_time is not null");
      return (Criteria) this;
    }

    public Criteria andCreateTimeEqualTo(Date value) {
      if(value != null) addCriterion("create_time =", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeNotEqualTo(Date value) {
      if(value != null) addCriterion("create_time <>", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeGreaterThan(Date value) {
      if(value != null) addCriterion("create_time >", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
      if(value != null) addCriterion("create_time >=", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeLessThan(Date value) {
      if(value != null) addCriterion("create_time <", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
      if(value != null) addCriterion("create_time <=", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeIn(List<Date> values) {
      if (values != null && ! values.isEmpty()) addCriterion("create_time in", values, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeNotIn(List<Date> values) {
      if (values != null && ! values.isEmpty()) addCriterion("create_time not in", values, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeBetween(Date head, Date tail) {
      if(head != null && tail != null) addCriterion("create_time between", head, tail, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeNotBetween(Date head, Date tail) {
      if(head != null && tail != null) addCriterion("create_time not between", head, tail, "createTime");
      return (Criteria) this;
    }

    public Criteria andAlterTimeIsNull() {
      addCriterion("alter_time is null");
      return (Criteria) this;
    }

    public Criteria andAlterTimeIsNotNull() {
      addCriterion("alter_time is not null");
      return (Criteria) this;
    }

    public Criteria andAlterTimeEqualTo(Date value) {
      if(value != null) addCriterion("alter_time =", value, "alterTime");
      return (Criteria) this;
    }

    public Criteria andAlterTimeNotEqualTo(Date value) {
      if(value != null) addCriterion("alter_time <>", value, "alterTime");
      return (Criteria) this;
    }

    public Criteria andAlterTimeGreaterThan(Date value) {
      if(value != null) addCriterion("alter_time >", value, "alterTime");
      return (Criteria) this;
    }

    public Criteria andAlterTimeGreaterThanOrEqualTo(Date value) {
      if(value != null) addCriterion("alter_time >=", value, "alterTime");
      return (Criteria) this;
    }

    public Criteria andAlterTimeLessThan(Date value) {
      if(value != null) addCriterion("alter_time <", value, "alterTime");
      return (Criteria) this;
    }

    public Criteria andAlterTimeLessThanOrEqualTo(Date value) {
      if(value != null) addCriterion("alter_time <=", value, "alterTime");
      return (Criteria) this;
    }

    public Criteria andAlterTimeIn(List<Date> values) {
      if (values != null && ! values.isEmpty()) addCriterion("alter_time in", values, "alterTime");
      return (Criteria) this;
    }

    public Criteria andAlterTimeNotIn(List<Date> values) {
      if (values != null && ! values.isEmpty()) addCriterion("alter_time not in", values, "alterTime");
      return (Criteria) this;
    }

    public Criteria andAlterTimeBetween(Date head, Date tail) {
      if(head != null && tail != null) addCriterion("alter_time between", head, tail, "alterTime");
      return (Criteria) this;
    }

    public Criteria andAlterTimeNotBetween(Date head, Date tail) {
      if(head != null && tail != null) addCriterion("alter_time not between", head, tail, "alterTime");
      return (Criteria) this;
    }

    public Criteria andStateIsNull() {
      addCriterion("`state` is null");
      return (Criteria) this;
    }

    public Criteria andStateIsNotNull() {
      addCriterion("`state` is not null");
      return (Criteria) this;
    }

    public Criteria andStateEqualTo(String value) {
      if(value != null) addCriterion("`state` =", value, "state");
      return (Criteria) this;
    }

    public Criteria andStateNotEqualTo(String value) {
      if(value != null) addCriterion("`state` <>", value, "state");
      return (Criteria) this;
    }

    public Criteria andStateGreaterThan(String value) {
      if(value != null) addCriterion("`state` >", value, "state");
      return (Criteria) this;
    }

    public Criteria andStateGreaterThanOrEqualTo(String value) {
      if(value != null) addCriterion("`state` >=", value, "state");
      return (Criteria) this;
    }

    public Criteria andStateLessThan(String value) {
      if(value != null) addCriterion("`state` <", value, "state");
      return (Criteria) this;
    }

    public Criteria andStateLessThanOrEqualTo(String value) {
      if(value != null) addCriterion("`state` <=", value, "state");
      return (Criteria) this;
    }

    public Criteria andStateLike(String value) {
      if(value != null) addCriterion("`state` like", value, "state");
      return (Criteria) this;
    }

    public Criteria andStateNotLike(String value) {
      if(value != null) addCriterion("`state` not like", value, "state");
      return (Criteria) this;
    }

    public Criteria andStateIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("`state` in", values, "state");
      return (Criteria) this;
    }

    public Criteria andStateNotIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("`state` not in", values, "state");
      return (Criteria) this;
    }

    public Criteria andStateBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("`state` between", head, tail, "state");
      return (Criteria) this;
    }

    public Criteria andStateNotBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("`state` not between", head, tail, "state");
      return (Criteria) this;
    }
  }

  public static class Criteria extends GeneratedCriteria {
    private BlogExample example;

    protected Criteria(BlogExample example) {
      super();
      this.example = example;
    }

    public BlogExample example() {
      return this.example;
    }
  }

  public static class Criterion {
    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}