//*****************************************************************************
// The file is automatically generated by the program, do not manually modify. 
//*****************************************************************************

package org.github.spring.base.example;

import java.util.ArrayList;
import java.util.List;

public class OauthClientDetailsExample {
  protected String orderByClause;

  protected boolean distinct;

  protected List<Criteria> oredCriteria;

  public OauthClientDetailsExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  public String getOrderByClause() {
    return orderByClause;
  }

  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  public boolean isDistinct() {
    return distinct;
  }

  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria(this);
    return criteria;
  }

  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andClientIdIsNull() {
      addCriterion("client_id is null");
      return (Criteria) this;
    }

    public Criteria andClientIdIsNotNull() {
      addCriterion("client_id is not null");
      return (Criteria) this;
    }

    public Criteria andClientIdEqualTo(String value) {
      if(value != null) addCriterion("client_id =", value, "clientId");
      return (Criteria) this;
    }

    public Criteria andClientIdNotEqualTo(String value) {
      if(value != null) addCriterion("client_id <>", value, "clientId");
      return (Criteria) this;
    }

    public Criteria andClientIdGreaterThan(String value) {
      if(value != null) addCriterion("client_id >", value, "clientId");
      return (Criteria) this;
    }

    public Criteria andClientIdGreaterThanOrEqualTo(String value) {
      if(value != null) addCriterion("client_id >=", value, "clientId");
      return (Criteria) this;
    }

    public Criteria andClientIdLessThan(String value) {
      if(value != null) addCriterion("client_id <", value, "clientId");
      return (Criteria) this;
    }

    public Criteria andClientIdLessThanOrEqualTo(String value) {
      if(value != null) addCriterion("client_id <=", value, "clientId");
      return (Criteria) this;
    }

    public Criteria andClientIdLike(String value) {
      if(value != null) addCriterion("client_id like", value, "clientId");
      return (Criteria) this;
    }

    public Criteria andClientIdNotLike(String value) {
      if(value != null) addCriterion("client_id not like", value, "clientId");
      return (Criteria) this;
    }

    public Criteria andClientIdIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("client_id in", values, "clientId");
      return (Criteria) this;
    }

    public Criteria andClientIdNotIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("client_id not in", values, "clientId");
      return (Criteria) this;
    }

    public Criteria andClientIdBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("client_id between", head, tail, "clientId");
      return (Criteria) this;
    }

    public Criteria andClientIdNotBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("client_id not between", head, tail, "clientId");
      return (Criteria) this;
    }

    public Criteria andResourceIdsIsNull() {
      addCriterion("resource_ids is null");
      return (Criteria) this;
    }

    public Criteria andResourceIdsIsNotNull() {
      addCriterion("resource_ids is not null");
      return (Criteria) this;
    }

    public Criteria andResourceIdsEqualTo(String value) {
      if(value != null) addCriterion("resource_ids =", value, "resourceIds");
      return (Criteria) this;
    }

    public Criteria andResourceIdsNotEqualTo(String value) {
      if(value != null) addCriterion("resource_ids <>", value, "resourceIds");
      return (Criteria) this;
    }

    public Criteria andResourceIdsGreaterThan(String value) {
      if(value != null) addCriterion("resource_ids >", value, "resourceIds");
      return (Criteria) this;
    }

    public Criteria andResourceIdsGreaterThanOrEqualTo(String value) {
      if(value != null) addCriterion("resource_ids >=", value, "resourceIds");
      return (Criteria) this;
    }

    public Criteria andResourceIdsLessThan(String value) {
      if(value != null) addCriterion("resource_ids <", value, "resourceIds");
      return (Criteria) this;
    }

    public Criteria andResourceIdsLessThanOrEqualTo(String value) {
      if(value != null) addCriterion("resource_ids <=", value, "resourceIds");
      return (Criteria) this;
    }

    public Criteria andResourceIdsLike(String value) {
      if(value != null) addCriterion("resource_ids like", value, "resourceIds");
      return (Criteria) this;
    }

    public Criteria andResourceIdsNotLike(String value) {
      if(value != null) addCriterion("resource_ids not like", value, "resourceIds");
      return (Criteria) this;
    }

    public Criteria andResourceIdsIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("resource_ids in", values, "resourceIds");
      return (Criteria) this;
    }

    public Criteria andResourceIdsNotIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("resource_ids not in", values, "resourceIds");
      return (Criteria) this;
    }

    public Criteria andResourceIdsBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("resource_ids between", head, tail, "resourceIds");
      return (Criteria) this;
    }

    public Criteria andResourceIdsNotBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("resource_ids not between", head, tail, "resourceIds");
      return (Criteria) this;
    }

    public Criteria andClientSecretIsNull() {
      addCriterion("client_secret is null");
      return (Criteria) this;
    }

    public Criteria andClientSecretIsNotNull() {
      addCriterion("client_secret is not null");
      return (Criteria) this;
    }

    public Criteria andClientSecretEqualTo(String value) {
      if(value != null) addCriterion("client_secret =", value, "clientSecret");
      return (Criteria) this;
    }

    public Criteria andClientSecretNotEqualTo(String value) {
      if(value != null) addCriterion("client_secret <>", value, "clientSecret");
      return (Criteria) this;
    }

    public Criteria andClientSecretGreaterThan(String value) {
      if(value != null) addCriterion("client_secret >", value, "clientSecret");
      return (Criteria) this;
    }

    public Criteria andClientSecretGreaterThanOrEqualTo(String value) {
      if(value != null) addCriterion("client_secret >=", value, "clientSecret");
      return (Criteria) this;
    }

    public Criteria andClientSecretLessThan(String value) {
      if(value != null) addCriterion("client_secret <", value, "clientSecret");
      return (Criteria) this;
    }

    public Criteria andClientSecretLessThanOrEqualTo(String value) {
      if(value != null) addCriterion("client_secret <=", value, "clientSecret");
      return (Criteria) this;
    }

    public Criteria andClientSecretLike(String value) {
      if(value != null) addCriterion("client_secret like", value, "clientSecret");
      return (Criteria) this;
    }

    public Criteria andClientSecretNotLike(String value) {
      if(value != null) addCriterion("client_secret not like", value, "clientSecret");
      return (Criteria) this;
    }

    public Criteria andClientSecretIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("client_secret in", values, "clientSecret");
      return (Criteria) this;
    }

    public Criteria andClientSecretNotIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("client_secret not in", values, "clientSecret");
      return (Criteria) this;
    }

    public Criteria andClientSecretBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("client_secret between", head, tail, "clientSecret");
      return (Criteria) this;
    }

    public Criteria andClientSecretNotBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("client_secret not between", head, tail, "clientSecret");
      return (Criteria) this;
    }

    public Criteria andScopeIsNull() {
      addCriterion("`scope` is null");
      return (Criteria) this;
    }

    public Criteria andScopeIsNotNull() {
      addCriterion("`scope` is not null");
      return (Criteria) this;
    }

    public Criteria andScopeEqualTo(String value) {
      if(value != null) addCriterion("`scope` =", value, "scope");
      return (Criteria) this;
    }

    public Criteria andScopeNotEqualTo(String value) {
      if(value != null) addCriterion("`scope` <>", value, "scope");
      return (Criteria) this;
    }

    public Criteria andScopeGreaterThan(String value) {
      if(value != null) addCriterion("`scope` >", value, "scope");
      return (Criteria) this;
    }

    public Criteria andScopeGreaterThanOrEqualTo(String value) {
      if(value != null) addCriterion("`scope` >=", value, "scope");
      return (Criteria) this;
    }

    public Criteria andScopeLessThan(String value) {
      if(value != null) addCriterion("`scope` <", value, "scope");
      return (Criteria) this;
    }

    public Criteria andScopeLessThanOrEqualTo(String value) {
      if(value != null) addCriterion("`scope` <=", value, "scope");
      return (Criteria) this;
    }

    public Criteria andScopeLike(String value) {
      if(value != null) addCriterion("`scope` like", value, "scope");
      return (Criteria) this;
    }

    public Criteria andScopeNotLike(String value) {
      if(value != null) addCriterion("`scope` not like", value, "scope");
      return (Criteria) this;
    }

    public Criteria andScopeIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("`scope` in", values, "scope");
      return (Criteria) this;
    }

    public Criteria andScopeNotIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("`scope` not in", values, "scope");
      return (Criteria) this;
    }

    public Criteria andScopeBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("`scope` between", head, tail, "scope");
      return (Criteria) this;
    }

    public Criteria andScopeNotBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("`scope` not between", head, tail, "scope");
      return (Criteria) this;
    }

    public Criteria andAuthorizedGrantTypesIsNull() {
      addCriterion("authorized_grant_types is null");
      return (Criteria) this;
    }

    public Criteria andAuthorizedGrantTypesIsNotNull() {
      addCriterion("authorized_grant_types is not null");
      return (Criteria) this;
    }

    public Criteria andAuthorizedGrantTypesEqualTo(String value) {
      if(value != null) addCriterion("authorized_grant_types =", value, "authorizedGrantTypes");
      return (Criteria) this;
    }

    public Criteria andAuthorizedGrantTypesNotEqualTo(String value) {
      if(value != null) addCriterion("authorized_grant_types <>", value, "authorizedGrantTypes");
      return (Criteria) this;
    }

    public Criteria andAuthorizedGrantTypesGreaterThan(String value) {
      if(value != null) addCriterion("authorized_grant_types >", value, "authorizedGrantTypes");
      return (Criteria) this;
    }

    public Criteria andAuthorizedGrantTypesGreaterThanOrEqualTo(String value) {
      if(value != null) addCriterion("authorized_grant_types >=", value, "authorizedGrantTypes");
      return (Criteria) this;
    }

    public Criteria andAuthorizedGrantTypesLessThan(String value) {
      if(value != null) addCriterion("authorized_grant_types <", value, "authorizedGrantTypes");
      return (Criteria) this;
    }

    public Criteria andAuthorizedGrantTypesLessThanOrEqualTo(String value) {
      if(value != null) addCriterion("authorized_grant_types <=", value, "authorizedGrantTypes");
      return (Criteria) this;
    }

    public Criteria andAuthorizedGrantTypesLike(String value) {
      if(value != null) addCriterion("authorized_grant_types like", value, "authorizedGrantTypes");
      return (Criteria) this;
    }

    public Criteria andAuthorizedGrantTypesNotLike(String value) {
      if(value != null) addCriterion("authorized_grant_types not like", value, "authorizedGrantTypes");
      return (Criteria) this;
    }

    public Criteria andAuthorizedGrantTypesIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("authorized_grant_types in", values, "authorizedGrantTypes");
      return (Criteria) this;
    }

    public Criteria andAuthorizedGrantTypesNotIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("authorized_grant_types not in", values, "authorizedGrantTypes");
      return (Criteria) this;
    }

    public Criteria andAuthorizedGrantTypesBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("authorized_grant_types between", head, tail, "authorizedGrantTypes");
      return (Criteria) this;
    }

    public Criteria andAuthorizedGrantTypesNotBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("authorized_grant_types not between", head, tail, "authorizedGrantTypes");
      return (Criteria) this;
    }

    public Criteria andWebServerRedirectUriIsNull() {
      addCriterion("web_server_redirect_uri is null");
      return (Criteria) this;
    }

    public Criteria andWebServerRedirectUriIsNotNull() {
      addCriterion("web_server_redirect_uri is not null");
      return (Criteria) this;
    }

    public Criteria andWebServerRedirectUriEqualTo(String value) {
      if(value != null) addCriterion("web_server_redirect_uri =", value, "webServerRedirectUri");
      return (Criteria) this;
    }

    public Criteria andWebServerRedirectUriNotEqualTo(String value) {
      if(value != null) addCriterion("web_server_redirect_uri <>", value, "webServerRedirectUri");
      return (Criteria) this;
    }

    public Criteria andWebServerRedirectUriGreaterThan(String value) {
      if(value != null) addCriterion("web_server_redirect_uri >", value, "webServerRedirectUri");
      return (Criteria) this;
    }

    public Criteria andWebServerRedirectUriGreaterThanOrEqualTo(String value) {
      if(value != null) addCriterion("web_server_redirect_uri >=", value, "webServerRedirectUri");
      return (Criteria) this;
    }

    public Criteria andWebServerRedirectUriLessThan(String value) {
      if(value != null) addCriterion("web_server_redirect_uri <", value, "webServerRedirectUri");
      return (Criteria) this;
    }

    public Criteria andWebServerRedirectUriLessThanOrEqualTo(String value) {
      if(value != null) addCriterion("web_server_redirect_uri <=", value, "webServerRedirectUri");
      return (Criteria) this;
    }

    public Criteria andWebServerRedirectUriLike(String value) {
      if(value != null) addCriterion("web_server_redirect_uri like", value, "webServerRedirectUri");
      return (Criteria) this;
    }

    public Criteria andWebServerRedirectUriNotLike(String value) {
      if(value != null) addCriterion("web_server_redirect_uri not like", value, "webServerRedirectUri");
      return (Criteria) this;
    }

    public Criteria andWebServerRedirectUriIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("web_server_redirect_uri in", values, "webServerRedirectUri");
      return (Criteria) this;
    }

    public Criteria andWebServerRedirectUriNotIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("web_server_redirect_uri not in", values, "webServerRedirectUri");
      return (Criteria) this;
    }

    public Criteria andWebServerRedirectUriBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("web_server_redirect_uri between", head, tail, "webServerRedirectUri");
      return (Criteria) this;
    }

    public Criteria andWebServerRedirectUriNotBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("web_server_redirect_uri not between", head, tail, "webServerRedirectUri");
      return (Criteria) this;
    }

    public Criteria andAuthoritiesIsNull() {
      addCriterion("authorities is null");
      return (Criteria) this;
    }

    public Criteria andAuthoritiesIsNotNull() {
      addCriterion("authorities is not null");
      return (Criteria) this;
    }

    public Criteria andAuthoritiesEqualTo(String value) {
      if(value != null) addCriterion("authorities =", value, "authorities");
      return (Criteria) this;
    }

    public Criteria andAuthoritiesNotEqualTo(String value) {
      if(value != null) addCriterion("authorities <>", value, "authorities");
      return (Criteria) this;
    }

    public Criteria andAuthoritiesGreaterThan(String value) {
      if(value != null) addCriterion("authorities >", value, "authorities");
      return (Criteria) this;
    }

    public Criteria andAuthoritiesGreaterThanOrEqualTo(String value) {
      if(value != null) addCriterion("authorities >=", value, "authorities");
      return (Criteria) this;
    }

    public Criteria andAuthoritiesLessThan(String value) {
      if(value != null) addCriterion("authorities <", value, "authorities");
      return (Criteria) this;
    }

    public Criteria andAuthoritiesLessThanOrEqualTo(String value) {
      if(value != null) addCriterion("authorities <=", value, "authorities");
      return (Criteria) this;
    }

    public Criteria andAuthoritiesLike(String value) {
      if(value != null) addCriterion("authorities like", value, "authorities");
      return (Criteria) this;
    }

    public Criteria andAuthoritiesNotLike(String value) {
      if(value != null) addCriterion("authorities not like", value, "authorities");
      return (Criteria) this;
    }

    public Criteria andAuthoritiesIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("authorities in", values, "authorities");
      return (Criteria) this;
    }

    public Criteria andAuthoritiesNotIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("authorities not in", values, "authorities");
      return (Criteria) this;
    }

    public Criteria andAuthoritiesBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("authorities between", head, tail, "authorities");
      return (Criteria) this;
    }

    public Criteria andAuthoritiesNotBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("authorities not between", head, tail, "authorities");
      return (Criteria) this;
    }

    public Criteria andAccessTokenValidityIsNull() {
      addCriterion("access_token_validity is null");
      return (Criteria) this;
    }

    public Criteria andAccessTokenValidityIsNotNull() {
      addCriterion("access_token_validity is not null");
      return (Criteria) this;
    }

    public Criteria andAccessTokenValidityEqualTo(Integer value) {
      if(value != null) addCriterion("access_token_validity =", value, "accessTokenValidity");
      return (Criteria) this;
    }

    public Criteria andAccessTokenValidityNotEqualTo(Integer value) {
      if(value != null) addCriterion("access_token_validity <>", value, "accessTokenValidity");
      return (Criteria) this;
    }

    public Criteria andAccessTokenValidityGreaterThan(Integer value) {
      if(value != null) addCriterion("access_token_validity >", value, "accessTokenValidity");
      return (Criteria) this;
    }

    public Criteria andAccessTokenValidityGreaterThanOrEqualTo(Integer value) {
      if(value != null) addCriterion("access_token_validity >=", value, "accessTokenValidity");
      return (Criteria) this;
    }

    public Criteria andAccessTokenValidityLessThan(Integer value) {
      if(value != null) addCriterion("access_token_validity <", value, "accessTokenValidity");
      return (Criteria) this;
    }

    public Criteria andAccessTokenValidityLessThanOrEqualTo(Integer value) {
      if(value != null) addCriterion("access_token_validity <=", value, "accessTokenValidity");
      return (Criteria) this;
    }

    public Criteria andAccessTokenValidityIn(List<Integer> values) {
      if (values != null && ! values.isEmpty()) addCriterion("access_token_validity in", values, "accessTokenValidity");
      return (Criteria) this;
    }

    public Criteria andAccessTokenValidityNotIn(List<Integer> values) {
      if (values != null && ! values.isEmpty()) addCriterion("access_token_validity not in", values, "accessTokenValidity");
      return (Criteria) this;
    }

    public Criteria andAccessTokenValidityBetween(Integer head, Integer tail) {
      if(head != null && tail != null) addCriterion("access_token_validity between", head, tail, "accessTokenValidity");
      return (Criteria) this;
    }

    public Criteria andAccessTokenValidityNotBetween(Integer head, Integer tail) {
      if(head != null && tail != null) addCriterion("access_token_validity not between", head, tail, "accessTokenValidity");
      return (Criteria) this;
    }

    public Criteria andRefreshTokenValidityIsNull() {
      addCriterion("refresh_token_validity is null");
      return (Criteria) this;
    }

    public Criteria andRefreshTokenValidityIsNotNull() {
      addCriterion("refresh_token_validity is not null");
      return (Criteria) this;
    }

    public Criteria andRefreshTokenValidityEqualTo(Integer value) {
      if(value != null) addCriterion("refresh_token_validity =", value, "refreshTokenValidity");
      return (Criteria) this;
    }

    public Criteria andRefreshTokenValidityNotEqualTo(Integer value) {
      if(value != null) addCriterion("refresh_token_validity <>", value, "refreshTokenValidity");
      return (Criteria) this;
    }

    public Criteria andRefreshTokenValidityGreaterThan(Integer value) {
      if(value != null) addCriterion("refresh_token_validity >", value, "refreshTokenValidity");
      return (Criteria) this;
    }

    public Criteria andRefreshTokenValidityGreaterThanOrEqualTo(Integer value) {
      if(value != null) addCriterion("refresh_token_validity >=", value, "refreshTokenValidity");
      return (Criteria) this;
    }

    public Criteria andRefreshTokenValidityLessThan(Integer value) {
      if(value != null) addCriterion("refresh_token_validity <", value, "refreshTokenValidity");
      return (Criteria) this;
    }

    public Criteria andRefreshTokenValidityLessThanOrEqualTo(Integer value) {
      if(value != null) addCriterion("refresh_token_validity <=", value, "refreshTokenValidity");
      return (Criteria) this;
    }

    public Criteria andRefreshTokenValidityIn(List<Integer> values) {
      if (values != null && ! values.isEmpty()) addCriterion("refresh_token_validity in", values, "refreshTokenValidity");
      return (Criteria) this;
    }

    public Criteria andRefreshTokenValidityNotIn(List<Integer> values) {
      if (values != null && ! values.isEmpty()) addCriterion("refresh_token_validity not in", values, "refreshTokenValidity");
      return (Criteria) this;
    }

    public Criteria andRefreshTokenValidityBetween(Integer head, Integer tail) {
      if(head != null && tail != null) addCriterion("refresh_token_validity between", head, tail, "refreshTokenValidity");
      return (Criteria) this;
    }

    public Criteria andRefreshTokenValidityNotBetween(Integer head, Integer tail) {
      if(head != null && tail != null) addCriterion("refresh_token_validity not between", head, tail, "refreshTokenValidity");
      return (Criteria) this;
    }

    public Criteria andAdditionalInformationIsNull() {
      addCriterion("additional_information is null");
      return (Criteria) this;
    }

    public Criteria andAdditionalInformationIsNotNull() {
      addCriterion("additional_information is not null");
      return (Criteria) this;
    }

    public Criteria andAdditionalInformationEqualTo(String value) {
      if(value != null) addCriterion("additional_information =", value, "additionalInformation");
      return (Criteria) this;
    }

    public Criteria andAdditionalInformationNotEqualTo(String value) {
      if(value != null) addCriterion("additional_information <>", value, "additionalInformation");
      return (Criteria) this;
    }

    public Criteria andAdditionalInformationGreaterThan(String value) {
      if(value != null) addCriterion("additional_information >", value, "additionalInformation");
      return (Criteria) this;
    }

    public Criteria andAdditionalInformationGreaterThanOrEqualTo(String value) {
      if(value != null) addCriterion("additional_information >=", value, "additionalInformation");
      return (Criteria) this;
    }

    public Criteria andAdditionalInformationLessThan(String value) {
      if(value != null) addCriterion("additional_information <", value, "additionalInformation");
      return (Criteria) this;
    }

    public Criteria andAdditionalInformationLessThanOrEqualTo(String value) {
      if(value != null) addCriterion("additional_information <=", value, "additionalInformation");
      return (Criteria) this;
    }

    public Criteria andAdditionalInformationLike(String value) {
      if(value != null) addCriterion("additional_information like", value, "additionalInformation");
      return (Criteria) this;
    }

    public Criteria andAdditionalInformationNotLike(String value) {
      if(value != null) addCriterion("additional_information not like", value, "additionalInformation");
      return (Criteria) this;
    }

    public Criteria andAdditionalInformationIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("additional_information in", values, "additionalInformation");
      return (Criteria) this;
    }

    public Criteria andAdditionalInformationNotIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("additional_information not in", values, "additionalInformation");
      return (Criteria) this;
    }

    public Criteria andAdditionalInformationBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("additional_information between", head, tail, "additionalInformation");
      return (Criteria) this;
    }

    public Criteria andAdditionalInformationNotBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("additional_information not between", head, tail, "additionalInformation");
      return (Criteria) this;
    }

    public Criteria andAutoapproveIsNull() {
      addCriterion("autoapprove is null");
      return (Criteria) this;
    }

    public Criteria andAutoapproveIsNotNull() {
      addCriterion("autoapprove is not null");
      return (Criteria) this;
    }

    public Criteria andAutoapproveEqualTo(String value) {
      if(value != null) addCriterion("autoapprove =", value, "autoapprove");
      return (Criteria) this;
    }

    public Criteria andAutoapproveNotEqualTo(String value) {
      if(value != null) addCriterion("autoapprove <>", value, "autoapprove");
      return (Criteria) this;
    }

    public Criteria andAutoapproveGreaterThan(String value) {
      if(value != null) addCriterion("autoapprove >", value, "autoapprove");
      return (Criteria) this;
    }

    public Criteria andAutoapproveGreaterThanOrEqualTo(String value) {
      if(value != null) addCriterion("autoapprove >=", value, "autoapprove");
      return (Criteria) this;
    }

    public Criteria andAutoapproveLessThan(String value) {
      if(value != null) addCriterion("autoapprove <", value, "autoapprove");
      return (Criteria) this;
    }

    public Criteria andAutoapproveLessThanOrEqualTo(String value) {
      if(value != null) addCriterion("autoapprove <=", value, "autoapprove");
      return (Criteria) this;
    }

    public Criteria andAutoapproveLike(String value) {
      if(value != null) addCriterion("autoapprove like", value, "autoapprove");
      return (Criteria) this;
    }

    public Criteria andAutoapproveNotLike(String value) {
      if(value != null) addCriterion("autoapprove not like", value, "autoapprove");
      return (Criteria) this;
    }

    public Criteria andAutoapproveIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("autoapprove in", values, "autoapprove");
      return (Criteria) this;
    }

    public Criteria andAutoapproveNotIn(List<String> values) {
      if (values != null && ! values.isEmpty()) addCriterion("autoapprove not in", values, "autoapprove");
      return (Criteria) this;
    }

    public Criteria andAutoapproveBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("autoapprove between", head, tail, "autoapprove");
      return (Criteria) this;
    }

    public Criteria andAutoapproveNotBetween(String head, String tail) {
      if(head != null && tail != null) addCriterion("autoapprove not between", head, tail, "autoapprove");
      return (Criteria) this;
    }
  }

  public static class Criteria extends GeneratedCriteria {
    private OauthClientDetailsExample example;

    protected Criteria(OauthClientDetailsExample example) {
      super();
      this.example = example;
    }

    public OauthClientDetailsExample example() {
      return this.example;
    }
  }

  public static class Criterion {
    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}